#!/usr/bin/env python3
"""Generate dependency-free Solidity interfaces and canonical constants."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
HEADER = "// SPDX-License-Identifier: MIT\n// Generated by scripts/generate.py. Do not edit.\npragma solidity >=0.8.4 <0.9.0;\n\n"


def interface_name(contract: str) -> str:
    return contract if len(contract) > 1 and contract[0] == "I" and contract[1].isupper() else "I" + contract


def render_constants(canonical: dict) -> dict[str, str]:
    addresses = [HEADER, "/// @notice Fixed system contract and precompile addresses from canonical.json.\n// Every hex literal is validated as exactly 20 bytes by the generator.\n// forge-lint: disable-start(unsafe-typecast)\nlibrary DiesisAddresses {\n"]
    for name, address in canonical["addresses"].items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", name) or not re.fullmatch(r"0x[0-9a-fA-F]{40}", address):
            raise ValueError(f"invalid canonical address: {name}={address}")
        addresses.append(f'    address internal constant {name} = address(bytes20(hex"{address[2:]}"));\n')
    addresses.append("}\n")
    chains = [HEADER, "/// @notice Chain IDs from canonical.json.\nlibrary DiesisChains {\n"]
    for name, chain in canonical["chains"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*", name) or type(chain["id"]) is not int or not 0 < chain["id"] < 2**256:
            raise ValueError(f"invalid canonical chain: {name}")
        chains.append(f"    uint256 internal constant {name.upper()} = {chain['id']};\n")
    chains.append("}\n")
    return {"src/DiesisAddresses.sol": "".join(addresses), "src/DiesisChains.sol": "".join(chains)}


def sync_files(root: Path, files: dict[str, str], check: bool) -> list[str]:
    owned = list((root / "src/interfaces").glob("*.sol"))
    stale = sorted(str(path.relative_to(root)) for path in owned if str(path.relative_to(root)) not in files)
    problems = [f"stale: {rel}" for rel in stale]
    for rel, content in sorted(files.items()):
        path = root / rel
        if not path.exists():
            problems.append(f"missing: {rel}")
        elif path.read_text() != content:
            problems.append(f"out of date: {rel}")
    if not check:
        for rel in stale:
            (root / rel).unlink()
        for rel, content in files.items():
            path = root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text() != content:
                path.write_text(content)
    return problems


def expected_files(artifacts: Path, canonical_path: Path, binary: str) -> dict[str, str]:
    config = json.loads((ROOT / "generation.json").read_text())
    version = subprocess.run([binary, "--version"], check=True, capture_output=True, text=True).stdout.strip()
    if version != f"abi-typegen {config['version']}":
        raise ValueError(f"abi-typegen {config['version']} is required; found {version!r}")
    files = {}
    # Require exactly one artifact per contract before invoking typegen. This
    # rejects missing/ambiguous input instead of silently generating a subset.
    with tempfile.TemporaryDirectory(prefix="diesis-sol-") as directory:
        temp = Path(directory)
        for name in config["contracts"]:
            matches = sorted(artifacts.rglob(f"{name}.json"))
            if len(matches) != 1:
                raise ValueError(f"expected one artifact for {name} in {artifacts}; found {len(matches)}")
        output = temp / "generated"
        subprocess.run([binary, "generate", "--artifacts", str(artifacts), "--contracts", ",".join(config["contracts"]), "--target", config["target"], "--out", str(output)], check=True)
        produced = {path.name: path for path in output.rglob("*.sol")}
        expected = {f"{interface_name(name)}.sol" for name in config["contracts"]}
        if set(produced) != expected:
            raise ValueError(f"unexpected generated interfaces: {sorted(produced)}; expected {sorted(expected)}")
        for name, path in produced.items():
            files[f"src/interfaces/{name}"] = path.read_text()
    canonical_text = canonical_path.read_text()
    files["canonical.json"] = canonical_text
    files.update(render_constants(json.loads(canonical_text)))
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing any SDK files")
    parser.add_argument("--artifacts", type=Path, help="compiled artifacts from the contracts source checkout")
    parser.add_argument("--canonical", type=Path, help="canonical.json source")
    args = parser.parse_args()
    contracts = Path(os.environ.get("DIESIS_CONTRACTS_DIR", ROOT / "../../diesis-core/diesis/contracts")).resolve()
    artifacts = args.artifacts or contracts / "out"
    sibling = ROOT.parent / "diesis-js/canonical.json"
    canonical = args.canonical or Path(os.environ.get("DIESIS_CANONICAL_FILE", sibling if sibling.exists() else ROOT / "canonical.json"))
    try:
        files = expected_files(artifacts.resolve(), canonical.resolve(), os.environ.get("ABI_TYPEGEN", "abi-typegen"))
        problems = sync_files(ROOT, files, args.check)
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"generation failed: {error}\n")
    if args.check and problems:
        parser.exit(1, "\n".join(problems) + "\nrun: python3 scripts/generate.py\n")
    print(f"{'up to date' if args.check else 'generated'}: {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
