// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisBuybackBurn {
    struct WindowState {
        uint64 windowStartBlock;
        uint64 windowEndBlock;
        uint64 windowLengthBlocks;
        uint8 chunksTotal;
        uint8 chunksRemaining;
        uint256 initialPending;
        uint256 twapAveragePrice;
    }

    error BuybackBurnCallFailed();

    error UnapprovedAsset();

    error WindowAlreadyOpen();

    error ZeroAmount();

    event AssetApproved(address indexed token);

    event BurnChunk(address indexed token, uint256 amount, uint256 limitPrice, uint64 block_);

    event DsBurned(uint256 amount, uint256 cumulativeBurnedDs);

    /// @notice Lifetime DS burned across all sources.
    function cumulativeBurnedDs() external view returns (uint256);

    /// @notice Last TWAP-average execution price recorded for `token`.
    /// @dev DS-quote, oracle scale. Updated incrementally on each successful      chunk emission; zero if no chunks have executed yet.
    function lastTwapAveragePrice(address token) external view returns (uint256);

    /// @notice Block at which the next TWAP window for `token` opens.
    /// @dev When a window is active, this returns the active window's end      block (the earliest block at which a fresh window may begin).      Returns zero when no window has ever been scheduled for `token`.
    function nextWindowStartBlock(address token) external view returns (uint64);

    /// @notice Read the pending (non-DS) accumulator for `token`.
    /// @dev DS deposits burn immediately and never accumulate; this returns      zero for DS.
    function pendingPurchaseByAsset(address token) external view returns (uint256);

    /// @notice Read the current window state, if any.
    /// @dev `windowLengthBlocks == 0` ⇒ no window active.
    function windowState(address token) external view returns (WindowState memory);
}
