// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisIssuanceAuction {
    struct PricedPerpRegistration {
        bytes32 marketId;
        address baseAsset;
        address quoteAsset;
        bytes32 evidenceHash;
        uint8 pricingVersion;
        uint64 priceDenominator;
    }

    struct UnpricedPerpRegistration {
        bytes32 marketId;
        address baseAsset;
        address quoteAsset;
        bytes32 evidenceHash;
    }

    struct PerpListingSlot {
        uint64 slotStartBlock;
        uint64 slotLengthBlocks;
        uint256 initialPriceUsdc;
        uint256 winningPriceUsdc;
        address currentWinner;
        bytes32 registrationDigest;
    }

    error AuctionNotSettled();

    error InvalidUnpricedPerpRegistration();

    error IssuanceAuctionCallFailed();

    error RegistrationConflict();

    event BidAccepted(address indexed bidder, bytes32 indexed marketId, bytes32 registrationDigest, uint256 priceUsdc);

    event SlotSettled(bytes32 indexed marketId, address indexed winner, bytes32 registrationDigest, uint256 priceUsdc);

    /// @notice Place a canonical-USDC bid bound to immutable priced units.
    /// @dev The native runtime debits msg.sender and retains the accepted      identity preimage. Successful admission and identical retries      return no data, as with bidUnpricedPerpListing.
    function bidPricedPerpListing(PricedPerpRegistration calldata registration) external;

    /// @notice Place a canonical-USDC bid bound to one perpetual registration.
    /// @dev The native runtime debits USDC; this selector is intentionally not      payable and accepts no caller-supplied winner.
    function bidUnpricedPerpListing(UnpricedPerpRegistration calldata registration) external;

    /// @notice Return the fixed V1 perpetual-listing price in USDC units.
    function currentPerpListingPrice() external view returns (uint256);

    /// @notice Read the active perpetual-listing slot and registration digest.
    function getPerpListingSlot() external view returns (PerpListingSlot memory);

    /// @notice Read the authenticated units retained by an accepted bid.
    /// @dev A proved legacy registration returns zero and one. Unknown records,      absent identity preimages, or deleted priced metadata revert.
    function getPerpRegistrationPricing(bytes32 marketId) external view returns (uint8 pricingVersion, uint64 priceDenominator);

    /// @notice Settle the elapsed perpetual-listing slot.
    /// @dev Native-runtime only: settlement atomically routes the accepted USDC      price (70% burn, 20% treasury, 10% validator rewards) and records      the winning registration with `DiesisPerpDeploy`. This selector is      ABI-visible for system dispatch but intentionally not forwarded by      `DiesisIssuanceAuction`. It returns no data; after the first due      transition, every repeat is a successful no-op over persisted state.
    function settlePerpListing() external;
}
