// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisShieldedPool {
    error CommitmentAlreadySeen();

    error CorruptRootHistory();

    error DuplicateCommitment();

    error DuplicateNullifier();

    error FeeExceedsDenomination();

    error IncorrectDepositAmount();

    error InsolventPool();

    error InsufficientOutstandingNotes();

    error InvalidActiveCount();

    error InvalidEncryptedPayloadLength();

    error InvalidProof();

    error InvalidProofLength();

    error InvalidRecipient();

    error InvalidRelayer();

    error InvalidVerifierIdentity();

    error NativeTransferFailed();

    error NonCanonicalField();

    error NonZeroInactiveSlot();

    error NotInitialized();

    error NullifierAlreadySpent();

    error PoseidonCallFailed();

    error ReentrantCall();

    error TreeIsFull();

    error UnknownMerkleRoot();

    error ZeroActiveField();

    event DepositV1(bytes32 indexed commitment, uint256 indexed leafIndex, bytes encryptedNote, bytes32 resultingRoot);

    event TransferV1(bytes32[2] nullifiers, bytes32[2] commitments, uint8 activeCount, uint256 firstOutputLeafIndex, bytes encryptedOutputs, bytes32 externalDataField, bytes32 resultingRoot);

    event WithdrawalV1(bytes32 indexed nullifier, address indexed recipient, address indexed relayer, uint256 fee, uint256 outstandingNotes);

    function DENOMINATION() external view returns (uint256);

    function DEPTH() external view returns (uint256);

    function ENCRYPTED_NOTE_BYTES() external view returns (uint256);

    function MAX_LEAVES() external view returns (uint256);

    function ROOT_HISTORY_SIZE() external view returns (uint256);

    function artifactClass() external pure returns (bytes32);

    function commitmentSeen(bytes32) external view returns (bool);

    function currentRootIndex() external view returns (uint256);

    function deposit(bytes32 commitment, bytes calldata encryptedNote) external payable;

    function filledSubtrees(uint256) external view returns (bytes32);

    function initialized() external view returns (bool);

    /// @notice Check if a root is in the history
    /// @param rootValue The root to check
    function isKnownRoot(bytes32 rootValue) external view returns (bool);

    function nextIndex() external view returns (uint256);

    function nullifiers(bytes32) external view returns (bool);

    function outstandingNotes() external view returns (uint256);

    function root() external view returns (bytes32);

    function rootHistory(uint256) external view returns (bytes32);

    function rootReferenceCount(bytes32) external view returns (uint16);

    function transact(bytes calldata proof, bytes32 merkleRoot, bytes32[2] calldata inputNullifiers, bytes32[2] calldata outputCommitments, uint8 activeCount, bytes calldata encryptedOutputs) external;

    function transferVerifier() external pure returns (address);

    function treeInitialized() external view returns (bool);

    function withdraw(bytes calldata proof, bytes32 merkleRoot, bytes32 nullifier, address recipient, address relayer, uint256 fee) external;

    function withdrawVerifier() external pure returns (address);

    function zeros(uint256) external view returns (bytes32);
}
