// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisPublicResolver {
    struct AgentRecord {
        bytes32 agentId;
        string endpoint;
        bytes publicKey;
        bytes32 capabilitiesHash;
        bytes32 policyHash;
        uint64 validFrom;
        uint64 validUntil;
        bool enabled;
    }

    struct PaymentRoute {
        uint256 chainId;
        address token;
        address recipient;
        uint16 priority;
        uint16 feeBpsLimit;
        bytes32 memoPolicy;
        bool enabled;
    }

    struct RouteRecord {
        bytes32 routeId;
        uint8 routeKind;
        bytes target;
        address contractTarget;
        bytes32 policyHash;
        bool wildcard;
        bool enabled;
    }

    error InvalidRoute();

    error NotAuthorized();

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error RecordTooLarge();

    error ResolverCallFailed();

    event AddrChanged(bytes32 indexed node, address indexed addrValue);

    event AddressChanged(bytes32 indexed node, uint256 indexed coinType, bytes newAddress);

    event AgentRecordChanged(bytes32 indexed node, bytes32 indexed agentId, string endpoint, bool enabled);

    event ContenthashChanged(bytes32 indexed node, bytes value);

    event ContractRecordChanged(bytes32 indexed node, bytes32 indexed role, address indexed target);

    event MulticoinAddrChanged(bytes32 indexed node, uint256 indexed coinType, bytes value);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event PaymentRouteChanged(bytes32 indexed node, bytes32 indexed routeId, address indexed recipient, bool enabled);

    event RouteRecordChanged(bytes32 indexed node, bytes32 indexed routeId, uint8 routeKind, bool wildcard, bool enabled);

    event TextChanged(bytes32 indexed node, string indexed key, string value);

    event TrustedWriterChanged(address indexed writer, bool approved);

    event WildcardPaymentRoutingChanged(bytes32 indexed node, bool approved);

    function DIESIS_EVM_COIN_TYPE() external view returns (uint256);

    function MAX_AGENT_RECORD_BYTES() external view returns (uint256);

    function MAX_CONTENTHASH_BYTES() external view returns (uint256);

    function MAX_MULTICOIN_ADDR_BYTES() external view returns (uint256);

    function MAX_RESOLVER_CALLS() external view returns (uint256);

    function MAX_ROUTE_TARGET_BYTES() external view returns (uint256);

    function MAX_TEXT_KEY_BYTES() external view returns (uint256);

    function MAX_TEXT_VALUE_BYTES() external view returns (uint256);

    function ROUTE_KIND_PAYMENT() external view returns (uint8);

    function addr(bytes32 node) external view returns (address);

    function addr(bytes32 node, uint256 coinType) external view returns (bytes memory);

    function agentRecord(bytes32 node, bytes32 agentId) external view returns (AgentRecord memory);

    function contenthash(bytes32 node) external view returns (bytes memory);

    function contractRecord(bytes32 node, bytes32 role) external view returns (address);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    function paymentRoute(bytes32 node, bytes32 routeId) external view returns (PaymentRoute memory);

    function registry() external view returns (address);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    function routeRecord(bytes32 node, bytes32 routeId) external view returns (RouteRecord memory);

    function setAddr(bytes32 node, uint256 coinType, bytes calldata value) external;

    function setAddr(bytes32 node, address value) external;

    function setAgentRecord(bytes32 node, bytes32 agentId, AgentRecord calldata record) external;

    function setContenthash(bytes32 node, bytes calldata value) external;

    function setContractRecord(bytes32 node, bytes32 role, address target) external;

    function setPaymentRoute(bytes32 node, bytes32 routeId, PaymentRoute calldata route) external;

    function setRecords(bytes32 node, bytes[] calldata calls) external;

    function setRouteRecord(bytes32 node, RouteRecord calldata record) external;

    function setText(bytes32 node, string calldata key, string calldata value) external;

    function setTrustedWriter(address writer, bool approved) external;

    function setWildcardPaymentRoutingAllowed(bytes32 node, bool approved) external;

    function text(bytes32 node, string calldata key) external view returns (string memory);

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    function trustedWriters(address writer) external view returns (bool approved);

    function wildcardPaymentRoutingAllowed(bytes32 node) external view returns (bool approved);
}
