// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisNameVerifier {
    struct NameAttestation {
        bytes32 node;
        bytes32 attestationType;
        address issuer;
        bytes32 subjectHash;
        bytes32 evidenceHash;
        uint64 issuedAt;
        uint64 validUntil;
        bytes extraData;
    }

    struct Attestation {
        bytes32 node;
        address subject;
        bytes32 kind;
        bytes32 digest;
        address issuer;
        uint64 issuedAt;
        uint64 expiresAt;
        bool revoked;
    }

    error AttestationAlreadySubmitted();

    error BadSignature();

    error NotIssuer();

    error UnknownAttestation();

    event AttestationRevoked(bytes32 indexed node, bytes32 indexed attestationHash, address indexed issuer);

    event AttestationSubmitted(bytes32 indexed node, bytes32 indexed attestationType, address indexed issuer, bytes32 attestationHash, uint64 validUntil);

    event Attested(bytes32 indexed attestationId, bytes32 indexed node, address indexed subject, bytes32 kind, bytes32 digest, uint64 expiresAt);

    event IssuerChanged(address indexed issuer, bool approved);

    event Revoked(bytes32 indexed attestationId);

    function attest(bytes32 node, address subject, bytes32 kind, bytes32 digest, uint64 expiresAt) external returns (bytes32 attestationId);

    function attestationDigest(NameAttestation calldata attestation) external view returns (bytes32);

    function attestationHash(NameAttestation calldata attestation) external pure returns (bytes32);

    function attestations(bytes32 node, bytes32 attestationType) external view returns (bytes32[] memory);

    function attestations(bytes32 attestationId) external view returns (Attestation memory);

    function isAttested(bytes32 node, bytes32 attestationType, address issuer) external view returns (bool);

    function isValid(bytes32 attestationId) external view returns (bool);

    function issuers(address issuer) external view returns (bool);

    function revoke(bytes32 attestationId) external;

    function revokeAttestation(bytes32 node, bytes32 attestationHash) external;

    function setIssuer(address issuer, bool approved) external;

    function submitAttestation(NameAttestation calldata attestation, bytes calldata signature) external;
}
