// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisStaking {
    struct EpochTransitionCertificateV1 {
        uint64 oldEpoch;
        bytes32 oldIdentityDigest;
        bytes32 nextIdentityDigest;
        uint64 activationBlockNumber;
        uint64 certificationBoundaryNumber;
        bytes32 certificationBoundaryParentHash;
        bytes32 certifiedCheckpointDigest;
        bytes signerBitmap;
        bytes aggregateSignature;
    }

    struct ValidatorIdentityV1 {
        uint256 validatorId;
        address consensusAddress;
        uint256 bondedStakeWei;
        uint64 votingPower;
        bytes blsPublicKey;
        bytes blsProofOfPossession;
        bytes vrfPublicKey;
        address quicTransportAddress;
        address relayerAddress;
        uint8 status;
    }

    struct CheckpointMetrics {
        uint256[] offlineDurations;
        uint256[] missedBlocks;
        uint256[] uptimeDurations;
        uint256[] txFeesOriginated;
        uint256[] slotFillRates;
        uint256[] inclusionRates;
        uint256[] leaderPerformances;
    }

    struct EpochIdentityV1 {
        uint16 version;
        uint64 chainId;
        bytes32 genesisHash;
        uint64 epoch;
        uint64 activationBlockNumber;
        bytes32 previousIdentityDigest;
        ValidatorIdentityV1[] validators;
    }

    struct RoleKeyBundle {
        address consensusAddress;
        bytes blsPublicKey;
        bytes blsProofOfPossession;
        bytes vrfPublicKey;
        address quicTransportAddress;
        address relayerAddress;
    }

    struct RoleProofBundle {
        bytes consensusSignature;
        bytes blsContextSignature;
        uint256 vrfX;
        uint256 vrfY;
        bytes vrfSignature;
        bytes quicSignature;
        bytes relayerSignature;
    }

    error AlreadyInitialized();

    error BootstrapValidatorSetRequiresCursor(uint256 count, uint256 maximum);

    error CheckpointOutOfRange();

    error ConfigurationBindingFixed();

    error CooldownNotElapsed();

    error DelegationCapExceeded();

    error DiscretionaryMintDisabled();

    error DuplicatePubkey();

    error DuplicateRequest();

    error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner);

    error ERC721InsufficientApproval(address operator, uint256 tokenId);

    error ERC721InvalidApprover(address approver);

    error ERC721InvalidOperator(address operator);

    error ERC721InvalidOwner(address owner);

    error ERC721InvalidReceiver(address receiver);

    error ERC721InvalidSender(address sender);

    error ERC721NonexistentToken(uint256 tokenId);

    error EpochAuthorityUnavailable();

    error FeeCustodyInsufficient();

    error InstantExitDisabled();

    error InsufficientStake();

    error InvalidAddress();

    error InvalidAmount();

    error InvalidFeeAccrualBlock();

    error InvalidParameter();

    error InvalidPubkeyFormat();

    error MetricLengthMismatch();

    error NativeTransferFailed();

    error NoOutstandingFees();

    error NoPendingRecovery();

    error NoRewardsToClaim();

    error NotPositionOwner();

    error OperatorBondTooLow();

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error RecoveryAlreadyPending();

    error RecoveryNotApproved();

    error RefundTooHigh();

    error RequestNotFound();

    error SamePosition();

    error SlashableValidatorInstantExitDisabled();

    error TreasuryUnconfigured();

    error Unauthorized();

    error ValidatorAlreadyExists();

    error ValidatorInactive();

    error ValidatorMismatch();

    error ValidatorNotFound();

    error ValidatorNotSlashable();

    error ValidatorStillAuthoritative();

    event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId);

    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);

    event CertifiedEpochApplied(uint256 indexed checkpoint, uint256 validatorCount, uint256 aggregateActiveStake);

    event CheckpointFeesRecorded(uint256 indexed checkpoint, uint256 indexed blockNumber, uint256 fee);

    event ExtraRewardAllocated(uint256 indexed checkpointId, uint256 received, uint256 distributed, uint256 burned);

    event KeyRecoveryApproved(address indexed oldAddress, address indexed newAddress, address indexed authorizer);

    event KeyRecoveryCancelled(address indexed oldAddress, address indexed newAddress);

    event KeyRecoveryExecuted(uint256 indexed validatorId, address indexed oldAddress, address indexed newAddress);

    event KeyRecoveryRequested(address indexed oldAddress, address indexed newAddress);

    event ObserverCallbackFailed(uint256 indexed validatorId, address indexed delegator);

    event OperatorTakeRateActivated(uint256 indexed validatorId, uint256 newRate);

    event OperatorTakeRateScheduled(uint256 indexed validatorId, uint256 newRate, uint256 effectiveCheckpoint);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event ParticipationPoolBpsUpdated(uint256 bps);

    event ParticipationRewards(uint256 indexed checkpoint, uint256 availabilityPool, uint256 participationPool, uint256[] composites);

    event RecoveryAuthorizerSet(address indexed authorizer);

    event RewardsCompounded(uint256 indexed tokenId, uint256 indexed toValidatorId, uint256 amount);

    event RewardsHarvested(uint256 indexed tokenId, uint256 indexed toValidatorId, address recipient, uint256 amount);

    event SlashRefundRatioUpdated(uint256 indexed validatorId, uint256 refundRatio);

    event StakeObserverSet(address indexed observer);

    event Staked(address indexed delegator, uint256 indexed toValidatorId, uint256 indexed tokenId, uint256 amount);

    event SubScoreWeightsUpdated(uint256[3] weights);

    event TokensBurned(address indexed burner, uint256 amount);

    event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);

    event TreasuryFeesFlushed(uint256 amount);

    event UnstakeCompleted(uint256 indexed tokenId, uint256 indexed toValidatorId, uint256 indexed requestId, uint256 amount, uint256 slashPenalty);

    event UnstakeRequested(uint256 indexed tokenId, uint256 indexed toValidatorId, uint256 indexed requestId, uint256 amount);

    event ValidatorRegistered(uint256 indexed validatorId, address indexed authority, uint256 atCheckpoint, uint256 atTime);

    event ValidatorStatusChanged(uint256 indexed validatorId, uint256 newMarks);

    event ValidatorSuspended(uint256 indexed validatorId, uint256 atCheckpoint, uint256 atTime, uint256 reason);

    function DIESIS_POSITION() external view returns (address);

    function EPOCH_AUTHORITY() external view returns (address);

    function MAX_REGISTERED_VALIDATORS() external view returns (uint256);

    /// @notice Maximum native security issuance per second, independent of governance configuration.
    function MAX_REWARD_STREAM_PER_SECOND() external view returns (uint256);

    /// @notice Minimum finalized checkpoints before any stake exit can complete.
    function MIN_EXIT_DELAY_CHECKPOINTS() external view returns (uint256);

    /// @notice Minimum wall-clock delay before any stake exit can complete.
    function MIN_EXIT_DELAY_SECONDS() external view returns (uint256);

    function _MARK_EQUIVOCATION() external view returns (uint16);

    function _MARK_EVIDENCE_MASK() external view returns (uint16);

    function _MARK_INACTIVE_MASK() external view returns (uint16);

    function _MARK_OPERATOR_REVIEW() external view returns (uint16);

    function _MARK_PROBATION_MASK() external view returns (uint16);

    function _MARK_PROTOCOL_BREACH() external view returns (uint16);

    function _MARK_SCORE_DRIFT() external view returns (uint16);

    function _MARK_SLASH_REVIEW() external view returns (uint16);

    function _MARK_UPTIME_DRIFT() external view returns (uint16);

    function _NODE_ACTIVE() external view returns (uint16);

    function _NODE_EXITING() external view returns (uint16);

    /// @notice Lifetime ordinary gas fees held in this contract's locked native balance.
    function accountedNativeFees() external view returns (uint256);

    /// @notice Settle accrued rewards without claiming them.
    function accrueRewards(uint256 tokenId) external;

    function activateValidatorEpoch() external returns (bool activated);

    function activeEpoch() external view returns (uint64);

    function activeEpochIdentityDigest() external view returns (bytes32);

    /// @notice Exact old-to-new pair approved by the independent recovery authorizer.
    function activeRecovery(address) external view returns (address);

    function activeRoleBundleId(uint256 validatorId) external view returns (bytes32);

    /// @notice Returns the aggregate active stake across all validators.
    function aggregateActiveStake() external view returns (uint256);

    function aggregateStake() external view returns (uint256);

    /// @notice Fund additional rewards for the currently open checkpoint.
    /// @dev The active validator set for the open checkpoint must already be committed.      The full contribution leaves logical supply immediately; claims      re-add only the distributable portion, so `burned` is the net burn.
    function allocateExtraReward(uint256 checkpoint, bool withBurn) external payable;

    function anchorLotByNode(uint256) external view returns (uint256);

    /// @dev Gives permission to `to` to transfer `tokenId` token to another account. The approval is cleared when the token is transferred. Only a single account can be approved at a time, so approving the zero address clears previous approvals. Requirements: - The caller must own the token or be an approved operator. - `tokenId` must exist. Emits an {Approval} event.
    function approve(address to, uint256 tokenId) external;

    /// @notice Approve the exact recovery pair previously configured by `oldAddress`.
    /// @dev Callable only by the configured, non-zero independent recovery authorizer.
    function approveKeyRecovery(address oldAddress, address newAddress) external;

    /// @dev Returns the number of tokens in ``owner``'s account.
    function balanceOf(address owner) external view returns (uint256);

    /// @notice Bootstrap a delegation at genesis (driver only).
    /// @return tokenId the new position NFT minted to `delegator`
    function bootstrapDelegation(address delegator, uint256 toValidatorId, uint256 stakeAmount) external returns (uint256 tokenId);

    /// @notice Bootstrap a validator at genesis (driver only).
    function bootstrapValidator(address auth, uint256 validatorId, bytes calldata pubkey, uint256 createdTime) external;

    /// @notice Burn tokens by accepting msg.value and removing it from gross supply.
    /// @dev The received value stays locked in this contract (no spend path exists for it), so decrementing grossSupply is what actually retires it from circulatingSupply(). The subtraction is clamped rather than reverting: burnTokens is on the patronage fee path (DiesisPatron._burnGrantFee), and a revert here would invalidate synchronous patron settlement for the transaction.
    function burnTokens() external payable;

    /// @notice Cancel the caller's pending recovery and any approval for it.
    /// @dev This remains available to the old key until the approved destination executes.
    function cancelKeyRecovery() external;

    function cancelPendingValidatorEpoch() external;

    function certifyValidatorEpoch(EpochTransitionCertificateV1 calldata certificate) external;

    /// @notice Circulating supply = gross supply - tokens burned to address(0).
    /// @dev Dynamically subtracts address(0).balance to account for all burn paths.
    function circulatingSupply() external view returns (uint256);

    /// @notice Ordinary fees accrued to an open or finalized checkpoint.
    function collectedCheckpointFees(uint256 checkpoint) external view returns (uint256);

    /// @notice Complete an unstake request and withdraw tokens (subject to cooldown + slash). Caller must own the position NFT.
    function completeUnstake(uint256 tokenId, uint256 requestId) external;

    /// @notice Complete unstake and send payout to recipient.
    /// @param tokenId The staking position NFT (owned by DiesisPosition).
    /// @param requestId The request identifier used in `requestUnstakeForPosition`.
    /// @param recipient The address to receive the payout.
    /// @return payout   The amount of native tokens paid out.
    function completeUnstakeForPosition(uint256 tokenId, uint256 requestId, address recipient) external returns (uint256 payout);

    /// @notice Re-stake pending rewards into the same position. Caller must own the position NFT.
    function compoundRewards(uint256 tokenId) external;

    /// @notice Compound rewards back into the position.
    /// @param tokenId The staking position NFT (owned by DiesisPosition).
    /// @return compounded The amount of rewards compounded.
    function compoundRewardsForPosition(uint256 tokenId) external returns (uint256 compounded);

    function config() external view returns (address);

    function consensusKeyByNode(uint256) external view returns (bytes memory);

    function epochCandidate(uint256 validatorId) external view returns (address operator, uint256 bonded, uint256 marks);

    function epochIdentityDigest(uint64 epoch) external view returns (bytes32);

    function epochIdentityPage(uint64 epoch, uint256 cursor, uint256 limit) external view returns (ValidatorIdentityV1[] memory);

    /// @notice Replace `oldAddress` as validator operator with the caller.
    /// @dev The caller must be the exact approved destination and must not already operate a validator.
    function executeKeyRecovery(address oldAddress) external;

    /// @notice Unstake requests keyed by (tokenId => requestID => request)
    function exitTickets(uint256, uint256) external view returns (uint128 amount, uint48 validatorId, uint40 checkpoint, uint40 timestamp);

    function expirePendingValidatorEpoch() external;

    /// @notice Finalize the current checkpoint with validator performance metrics. Called by the Rust node as a system transaction (msg.sender == address(0)).
    function finalizeCheckpoint(CheckpointMetrics calldata metrics) external;

    function finalizeValidatorWithdrawal(uint256 validatorId) external;

    function flushTreasuryFees() external;

    /// @dev Returns the account approved for `tokenId` token. Requirements: - `tokenId` must exist.
    function getApproved(uint256 tokenId) external view returns (address);

    /// @notice Claim all pending rewards for a position. Caller must own the position NFT. Rewards are sent to the NFT owner.
    function harvestRewards(uint256 tokenId) external;

    /// @notice Harvest rewards and send to recipient.
    /// @param tokenId The staking position NFT (owned by DiesisPosition).
    /// @param recipient The address to receive the rewards.
    /// @return reward   The amount of rewards harvested.
    function harvestRewardsForPosition(uint256 tokenId, address recipient) external returns (uint256 reward);

    /// @notice Add stake to an existing staking position controlled by DiesisPosition.
    /// @param tokenId The staking position NFT (owned by DiesisPosition).
    function increaseStakeForPosition(uint256 tokenId) external payable;

    /// @notice Initialize the staking contract at genesis.
    function initialize(uint256 finalizedCheckpoint, uint256 _totalSupply, address configContract, address owner_) external;

    function initializeEpochZero(EpochIdentityV1 calldata identity, RoleKeyBundle[] calldata bundles, RoleProofBundle[] calldata proofs) external returns (bool epochInitialized);

    function initialized() external view returns (bool);

    /// @notice Retained controller selector; instant exits cannot bypass delayed slashing.
    /// @dev Use requestUnstakeForPosition and completeUnstakeForPosition instead.
    function instantUnstakeForPosition(uint256 tokenId, uint256 amount, uint256 fee, address recipient) external returns (uint256 payout);

    /// @dev Returns if the `operator` is allowed to manage all of the assets of `owner`. See {setApprovalForAll}
    function isApprovedForAll(address owner, address operator) external view returns (bool);

    function isSlashable(uint256 validatorId) external view returns (bool);

    /// @notice Last block whose ordinary gas fees were recorded by the node.
    function lastFeeAccrualBlock() external view returns (uint256);

    function latestFinalizedCheckpoint() external view returns (uint256);

    /// @notice Create an empty staking position for atomic splits (controller version).
    /// @param validatorId The validator the new position is assigned to.
    /// @return tokenId The newly minted staking position NFT (owned by DiesisPosition, 0 stake).
    function mintEmptyPositionForSplit(uint256 validatorId) external returns (uint256 tokenId);

    /// @notice Retired discretionary issuance selector. Security and bootstrap issuance have separate bounds.
    function mintTokens(uint256 amount) external;

    /// @dev Returns the token collection name.
    function name() external view returns (string memory);

    function nextPositionId() external view returns (uint256);

    function nextValidatorId() external view returns (uint256);

    function nodeByConsensusKey(bytes calldata) external view returns (uint256);

    function nodeIdByOperator(address) external view returns (uint256);

    function nodeLedger(uint256 validatorId) external view returns (address operator, uint256 marks, uint256 bonded, uint256 joinedCheckpoint, uint256 joinedAt, uint256 heldAt, uint256 heldCheckpoint);

    /// @notice Per-validator operator cut override (0 means use global default from DiesisConfig).
    function operatorTakeRateByNode(uint256) external view returns (uint256);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    /// @dev Returns the owner of the `tokenId` token. Requirements: - `tokenId` must exist.
    function ownerOf(uint256 tokenId) external view returns (address);

    /// @notice Fraction of checkpoint reward budget allocated to participation pool (default 3000 = 30%)
    function participationPoolBps() external view returns (uint256);

    function pendingEpochCertificationFields() external view returns (uint64 oldEpoch, bytes32 oldIdentityDigest, bytes32 nextIdentityDigest, uint64 activationBlockNumber, uint64 certificationBoundaryNumber, bytes32 certificationBoundaryParentHash, bytes32 certifiedCheckpointDigest, bool epochCertified);

    /// @notice Checkpoint at which the pending operator cut change takes effect.
    function pendingOperatorTakeCheckpoint(uint256) external view returns (uint256);

    /// @notice Pending operator cut change: validatorId → new rate.
    function pendingOperatorTakeRate(uint256) external view returns (uint256);

    /// @notice Destination preconfigured by the current operator, keyed by its old address.
    function pendingRecovery(address) external view returns (address);

    function pendingRoleBundleId(uint256 validatorId) external view returns (bytes32);

    function pendingTreasuryFees() external view returns (uint256);

    /// @notice Account for native DS issued by the canonical bootstrap oracle.
    /// @dev The oracle calls this atomically with its capped balance credits.
    function recordBootstrapMint(uint256 amount) external;

    /// @notice Account for one committed block's ordinary fees already credited by the node.
    /// @dev Transaction settlement credits the full charged fee into locked staking custody. Sponsored fees remain in Patron and must never enter this route. The system caller attests the ordinary fee total; the balance bound is an additional consistency check, not a replacement for execution validation because staking also holds stake deposits.
    function recordCheckpointFees(uint256 checkpoint, uint256 blockNumber, uint256 fee) external;

    function recordEpochCertificationBoundary(uint64 boundaryNumber, bytes32 boundaryParentHash, bytes32 checkpointDigest) external returns (bool recorded);

    function recoveryAuthorizer() external view returns (address);

    /// @notice Register a new validator with a public key.
    /// @return validatorId the new validator ID
    /// @return tokenId     the operator bond position NFT minted to msg.sender
    function registerValidator(bytes calldata pubkey) external payable returns (uint256 validatorId, uint256 tokenId);

    function registerValidatorRoleKeys(uint256 validatorId, uint64 targetEpoch, RoleKeyBundle calldata keys, RoleProofBundle calldata proofs) external returns (bytes32 bundleId);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    function requestKeyRecovery(address newAddress) external;

    /// @notice Request to unstake `amount` from a position NFT. Caller must own the position NFT.
    function requestUnstake(uint256 tokenId, uint256 requestId, uint256 amount) external;

    /// @notice Request unstake for a position controlled by DiesisPosition.
    /// @param tokenId The staking position NFT (owned by DiesisPosition).
    /// @param requestId Caller-chosen request identifier (must be unique per tokenId).
    /// @param amount Wei to undelegate.
    function requestUnstakeForPosition(uint256 tokenId, uint256 requestId, uint256 amount) external;

    /// @notice Latest checkpoint through which rewards have been settled for each position
    function rewardsAccruedThrough(uint256) external view returns (uint256);

    function roleDigest(uint256 validatorId, uint64 targetEpoch, uint8 role, bytes calldata publicIdentity) external view returns (bytes32);

    function roleKeyBundle(bytes32 bundleId) external view returns (RoleKeyBundle memory);

    /// @dev Safely transfers `tokenId` token from `from` to `to`, checking first that contract recipients are aware of the ERC-721 protocol to prevent tokens from being forever locked. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must exist and be owned by `from`. - If the caller is not `from`, it must have been allowed to move this token by either {approve} or   {setApprovalForAll}. - If `to` refers to a smart contract, it must implement {IERC721Receiver-onERC721Received}, which is called upon   a safe transfer. Emits a {Transfer} event.
    function safeTransferFrom(address from, address to, uint256 tokenId) external;

    /// @dev Safely transfers `tokenId` token from `from` to `to`. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must exist and be owned by `from`. - If the caller is not `from`, it must be approved to move this token by either {approve} or {setApprovalForAll}. - If `to` refers to a smart contract, it must implement {IERC721Receiver-onERC721Received}, which is called upon   a safe transfer. Emits a {Transfer} event.
    function safeTransferFrom(address from, address to, uint256 tokenId, bytes calldata data) external;

    function scheduleValidatorEpoch(uint64 activationBlockNumber) external;

    /// @dev Approve or remove `operator` as an operator for the caller. Operators can call {transferFrom} or {safeTransferFrom} for any token owned by the caller. Requirements: - The `operator` cannot be the address zero. Emits an {ApprovalForAll} event.
    function setApprovalForAll(address operator, bool approved) external;

    /// @notice Configuration is bound once by initialization or canonical genesis storage.
    function setConfigContract(address configContract) external;

    /// @notice Schedule an operator reward cut change for a validator.
    /// @dev Takes effect after the next checkpoint finalization (1-checkpoint cooldown).      Only callable by the validator's authority address.      Rate is capped at 20% (OPERATOR_TAKE_RATE_UPPER from DiesisConfig).      Upward changes are capped at 1 percentage point per checkpoint; reductions      can be scheduled immediately.
    /// @param validatorId The validator to update.
    /// @param rate The new operator cut as a fraction of 1e18 (e.g. 0.2e18 = 20%).
    function setOperatorTakeRate(uint256 validatorId, uint256 rate) external;

    /// @notice Update the participation pool share of checkpoint rewards.
    function setParticipationPoolBps(uint256 bps) external;

    function setRecoveryAuthorizer(address auth) external;

    function setSlashRefundRatio(uint256 validatorId, uint256 refundRatio) external;

    function setStakeObserver(address observer) external;

    /// @notice Update the weights for participation sub-scores.
    function setSubScoreWeights(uint256[3] calldata weights) external;

    function setTreasury(address treasury_) external;

    function slashRefundRatio(uint256) external view returns (uint256);

    /// @notice Delegate native tokens to a validator.
    /// @return tokenId the new position NFT minted to msg.sender
    function stake(uint256 toValidatorId) external payable returns (uint256 tokenId);

    /// @notice Create a new staking position controlled by DiesisPosition.
    /// @param toValidatorId The validator to delegate to.
    /// @return tokenId The newly minted staking position NFT (owned by DiesisPosition).
    function stakeForPosition(uint256 toValidatorId) external payable returns (uint256 tokenId);

    /// @notice Returns (validatorId, amount, entryCheckpoint) for a stake lot.
    /// @param tokenId The ERC-721 stake lot to query.
    /// @return validatorId The validator the position delegates to.
    /// @return stakeAmount Current delegated amount in wei.
    /// @return entryCheckpoint  Checkpoint when position was created.
    function stakeLots(uint256 tokenId) external view returns (uint256 validatorId, uint256 stakeAmount, uint256 entryCheckpoint);

    function stakeObserver() external view returns (address);

    /// @notice Weights for participation sub-scores [slotFill, inclusion, leader] summing to 10000
    function subScoreWeights(uint256) external view returns (uint256);

    /// @dev Returns true if this contract implements the interface defined by `interfaceId`. See the corresponding https://eips.ethereum.org/EIPS/eip-165#how-interfaces-are-identified[ERC section] to learn more about how these ids are created. This function call must use less than 30 000 gas.
    function supportsInterface(bytes4 interfaceId) external view returns (bool);

    /// @notice Suspend (deactivate) a validator with a governance-approved evidence mark.
    function suspendValidator(uint256 validatorId, uint256 reason) external;

    /// @notice Atomically re-delegate stake from one position to another on the same validator.
    /// @dev Both positions must be on the same validator. No unbonding delay.
    /// @param fromTokenId The source position NFT.
    /// @param toTokenId The destination position NFT.
    /// @param swapAmount Wei to move.
    function swapDelegate(uint256 fromTokenId, uint256 toTokenId, uint256 swapAmount) external;

    /// @notice Swap stake between two positions (controller version).
    /// @param fromTokenId Source position NFT.
    /// @param toTokenId Destination position NFT.
    /// @param swapAmount Wei to move.
    function swapDelegateForPosition(uint256 fromTokenId, uint256 toTokenId, uint256 swapAmount) external;

    /// @dev Returns the token collection symbol.
    function symbol() external view returns (string memory);

    /// @dev Returns the Uniform Resource Identifier (URI) for `tokenId` token.
    function tokenURI(uint256 tokenId) external view returns (string memory);

    /// @dev Transfers `tokenId` token from `from` to `to`. WARNING: Note that the caller is responsible to confirm that the recipient is capable of receiving ERC-721 or else they may be permanently lost. Usage of {safeTransferFrom} prevents loss, though the caller must understand this adds an external call which potentially creates a reentrancy vulnerability. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must be owned by `from`. - If the caller is not `from`, it must be approved to move this token by either {approve} or {setApprovalForAll}. Emits a {Transfer} event.
    function transferFrom(address from, address to, uint256 tokenId) external;

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    function treasury() external view returns (address);

    /// @notice View pending rewards for a position.
    function unclaimedRewards(uint256 tokenId) external view returns (uint256);

    /// @notice Request certified exclusion from the validator set.
    function withdrawValidator(uint256 validatorId) external;
}
