// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisSettlement {
    struct TradingKeyAuth {
        bytes32 header;
        uint256 maxOrderNotional;
        bytes32 allowedMarketsMask;
    }

    event Deposit(address indexed user, address indexed token, uint256 amount);

    event NonceCancelled(address indexed user, uint256 nonce);

    event PerpBackstopFunded(address indexed funder, bytes32 indexed marketId, address indexed quoteToken, uint256 amount, bytes32 transactionId);

    event TradingKeyRegistered(address indexed owner, address indexed tradingKey, uint64 validUntil, uint128 maxOrderNotional, bytes32 allowedMarketsMask, bool canWithdraw);

    event TradingKeyRevoked(address indexed owner, address indexed tradingKey);

    event Withdrawal(address indexed user, address indexed token, uint256 amount);

    /// @notice Authorize one ordinary Ethereum sender as a scoped V2 session key.
    /// @dev A zero maximum is uncapped. Principal is always `msg.sender`.
    function authorizeSessionKey(address sessionKey, uint256 actionScope, uint64 validUntil, uint256 maxNotionalOrSpend, bytes32 allowedMarketsMask) external returns (uint64 generation);

    function availableBalance(address user, address token) external view returns (uint256 available);

    function cancelNonceWord(uint248 wordPos) external;

    function cancelOrderNonce(uint256 nonce) external;

    /// @notice Credit a generic ERC-20 settlement balance on behalf of the router.
    /// @dev Callable only by the fixed `DiesisSettlementRouter` address. The router has already pulled `amount` of `token` into its own custody, so this selector only mutates the ledger — it never touches token storage. Reverts on a zero `user`, zero `token`, or zero `amount`.
    function creditRouterDeposit(address user, address token, uint256 amount) external;

    /// @notice Debit a generic ERC-20 settlement balance on behalf of the router.
    /// @dev Callable only by the fixed `DiesisSettlementRouter` address. The ledger debit runs before the router releases custody; a reverted token transfer rolls this mutation back atomically. Preserves the locked-balance invariant (`balance - locked >= amount`) and reverts on a zero `user`, zero `token`, or zero `amount`.
    function debitRouterWithdrawal(address user, address token, uint256 amount) external;

    /// @notice Move supported precompile-native tokens into the exchange settlement ledger.
    /// @dev Current runtime support is limited to WDS and liquid-staked DS precompile tokens.
    function deposit(address token, uint256 amount) external;

    /// @notice Permanently contribute already-deposited quote collateral to a perpetual market's canonical liquidation backstop.
    /// @dev `nonce` shares the settlement replay bitmap with other user-owned actions.
    function fundPerpBackstop(bytes32 marketId, uint256 amount, uint256 nonce) external returns (bytes32 transactionId);

    function getTradingKeyAuth(address owner, address tradingKey) external view returns (TradingKeyAuth memory auth);

    function isNonceUsed(address user, uint256 nonce) external view returns (bool used);

    function registerTradingKey(address tradingKey, uint64 validUntil, uint128 maxOrderNotional, bytes32 allowedMarketsMask, bool canWithdraw) external;

    /// @notice Revoke a V2 session key and advance its invalidating generation.
    function revokeSessionKey(address sessionKey) external returns (uint64 generation);

    function revokeTradingKey(address tradingKey) external;

    function totalBalance(address user, address token) external view returns (uint256 total);

    /// @notice Move unlocked settlement balance back to the caller's precompile-native token balance.
    function withdraw(address token, uint256 amount) external;
}
