// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisReverseRegistrar {
    error InvalidName();

    error NotAuthorized();

    event ControllerChanged(address indexed controller, bool approved);

    event ReverseNameChanged(address indexed addr, string name);

    function controllers(address controller) external view returns (bool);

    function name(address addr) external view returns (string memory);

    function node(address addr) external pure returns (bytes32);

    function setController(address controller, bool approved) external;

    function setName(string calldata name_) external returns (bytes32 node);

    function setNameForAddr(address addr, string calldata name_) external returns (bytes32 node);
}
