// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisMargin {
    event AutoDeleverage(bytes32 indexed marketId, address indexed deleveraged, address indexed counterparty, uint256 size, uint256 price);

    event Liquidation(bytes32 indexed marketId, address indexed trader, uint256 size, uint256 price, uint256 penalty);

    /// @notice System-owned canonical frontier resolution. External callers are rejected.
    function resolvePerpProtection(bytes32 marketId) external returns (bytes32 transactionId);
}
