// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisNamePolicy {
    error NotAuthorized();

    error NotGuardian();

    error RecoveryDisabled();

    error RecoveryNotReady();

    error TransferLocked();

    event GuardianChanged(bytes32 indexed node, address indexed guardian, bool approved);

    event NameRecovered(bytes32 indexed node, bytes32 indexed requestId, address indexed newOwner);

    event RecoveryApproved(bytes32 indexed node, bytes32 indexed requestId, address indexed guardian, address newOwner, uint8 approvals, uint64 executeAfter);

    event RecoveryCancelled(bytes32 indexed node, bytes32 indexed requestId);

    event RecoveryConfigChanged(bytes32 indexed node, uint8 threshold, uint64 delay, address fallbackOwner, bool enabled);

    event TransferLockChanged(bytes32 indexed node, uint64 lockedUntil);

    function approveRecovery(bytes32 node, address newOwner) external returns (bytes32 requestId);

    function cancelRecovery(bytes32 node, address newOwner) external;

    function finalizeRecovery(bytes32 node, address newOwner) external;

    function guardedTransfer(bytes32 node, address newOwner) external;

    function guardians(bytes32 node, address guardian) external view returns (bool);

    function isTransferLocked(bytes32 node) external view returns (bool);

    function recoveryDelay(bytes32 node) external view returns (uint64);

    function recoveryEnabled(bytes32 node) external view returns (bool);

    function recoveryFallbackOwner(bytes32 node) external view returns (address);

    function recoveryThreshold(bytes32 node) external view returns (uint8);

    function setGuardian(bytes32 node, address guardian, bool approved) external;

    function setRecoveryConfig(bytes32 node, uint8 threshold, uint64 delay, address fallbackOwner, bool enabled) external;

    function setTransferLock(bytes32 node, uint64 lockedUntil) external;

    function transferLockUntil(bytes32 node) external view returns (uint64);
}
