// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisOperatorBond {
    struct BondInfo {
        address operator;
        bytes32 marketId;
        uint256 bondDs;
        uint64 releaseUnlockBlock;
    }

    event BondPosted(address indexed operator, bytes32 indexed marketId, uint256 bondDs);

    event BondSlashed(bytes32 indexed marketId, uint256 amountDs);

    event ReleaseFinalized(bytes32 indexed marketId, uint256 refundedDs);

    event ReleaseRequested(bytes32 indexed marketId, uint64 unlockBlock);

    /// @notice Finalize a previously requested release and receive the refund.
    /// @dev Reverts before the unlock block or if no release is pending.
    function finalizeRelease(bytes32 marketId) external;

    /// @notice Read the public bond record for `marketId`.
    function getBond(bytes32 marketId) external view returns (BondInfo memory);

    /// @notice Post the operator bond for `marketId` with `msg.value` DS.
    /// @dev `msg.value` must equal exactly 50,000 DS. Reverts if a bond already      exists for `marketId`.
    function postBond(bytes32 marketId) external payable;

    /// @notice Request voluntary release of the bond.
    /// @dev Subject to a 30-day timelock. Pending claims against the backstop      must be resolved before the operator can finalize.
    function requestRelease(bytes32 marketId) external;
}
