// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisSpotBook {
    event BatchAuctionCleared(bytes32 indexed marketId, uint256 clearingPrice, uint256 totalVolume, uint256 residualOrders);

    event ExchangeActionAccepted(bytes16 indexed clientActionId, uint16 indexed actionIndex, uint8 actionTag, bytes32 indexed marketId, address principal, bytes32 resultId);

    event ExchangeActionRejected(bytes16 indexed clientActionId, uint16 indexed actionIndex, uint8 actionTag, bytes32 indexed marketId, address principal, uint16 reasonCode, bytes32 context);

    event ExchangeL3Mutation(bytes32 indexed marketId, bytes32 indexed orderId, address indexed trader, uint8 mutation, uint8 side, uint64 priceTicks, uint64 quantityLots, uint64 remainingLots);

    event ExchangeTradeFill(bytes32 indexed marketId, bytes32 indexed makerOrderId, bytes32 indexed takerOrderId, address maker, address taker, uint8 aggressorSide, uint64 priceTicks, uint64 quantityLots);

    event OrderCancelled(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader);

    event OrderFilled(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader, uint256 fillQty, uint256 fillPrice, uint256 remainingAmount, bool complete);

    event OrderPlaced(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader, uint8 side, uint256 price, uint256 amount, uint8 flags);

    event StopOrderTriggered(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader, uint256 triggerPrice, uint256 activationPrice);

    /// @notice Amend an active order owned by the caller.
    /// @dev Cancel-and-replace preserving the original `orderId`. Preserving the      id keeps user/market indexes and signed-intent nonce mappings stable.      Requires the original market to still be active and new price/amount      to be nonzero.
    /// @param orderId Existing order id.
    /// @param newPrice New limit price in ticks.
    /// @param newAmount New base quantity in lots.
    /// @param newFlags Replacement order flags.
    /// @return newOrderId Equal to `orderId`; retained for ABI compatibility with cancel-and-replace clients.
    function amendOrder(bytes32 orderId, uint256 newPrice, uint256 newAmount, uint8 newFlags) external returns (bytes32 newOrderId);

    /// @notice Cancel an active order owned by the caller.
    /// @dev Releases the order's locked collateral and clears the order storage.      Historical user and market order lists may still contain the order id;      clients should filter by order existence. Cancelling a dormant signed      stop removes its bounded stop-index membership and releases its lock.
    /// @param orderId Canonical order identifier.
    function cancelOrder(bytes32 orderId) external;

    /// @notice Execute a one-sided legacy spot fill.
    /// @dev System-only in production. Kept for compatibility and recovery tests.
    function executeSpotFill(bytes32 orderId, uint256 fillPrice, uint256 fillQty) external returns (uint256 filledQty, uint256 executionPrice);

    /// @notice Atomically settle a matched maker/taker spot trade.
    /// @dev System-only. Emits one `OrderFilled` event per side and clears completed orders.
    function executeSpotTrade(bytes32 makerOrderId, bytes32 takerOrderId, uint256 fillPrice, uint256 fillQty) external returns (uint256 filledQty, uint256 executionPrice);

    /// @notice Finalize an ended opening auction and return the market to active trading.
    /// @dev System-only. Runs the batch auction, settles crossing orders, restores      residual live orders into the continuous BBO cache, emits      `BatchAuctionCleared`, and stores final auction totals.
    function finalizeOpeningAuction(bytes32 marketId) external returns (uint256 clearingPrice, uint256 totalVolume);

    /// @notice Return the best ask stored in the on-chain BBO cache.
    /// @param marketId Canonical market identifier.
    /// @return priceTicks Best ask price in ticks, or zero when absent.
    /// @return amountLots Aggregate quantity at the best ask, or zero when absent.
    function getBestAsk(bytes32 marketId) external view returns (uint256 priceTicks, uint256 amountLots);

    /// @notice Return the best bid stored in the on-chain BBO cache.
    /// @param marketId Canonical market identifier.
    /// @return priceTicks Best bid price in ticks, or zero when absent.
    /// @return amountLots Aggregate quantity at the best bid, or zero when absent.
    function getBestBid(bytes32 marketId) external view returns (uint256 priceTicks, uint256 amountLots);

    /// @notice Return stored opening-auction state for a market.
    function getOpeningAuction(bytes32 marketId) external view returns (uint64 startBlock, uint64 endBlock, uint256 referencePrice, bool finalized, uint256 clearingPrice, uint256 totalVolume);

    /// @notice Return on-chain book depth.
    /// @dev Runtime returns real best-bid/best-ask data at level 0 only. Levels 1+      are zero-filled; full multi-level depth is available over exchange RPC.
    function getOrderBookDepth(bytes32 marketId, uint8 levels) external view returns (uint256[] memory bidPrices, uint256[] memory bidAmounts, uint256[] memory askPrices, uint256[] memory askAmounts);

    /// @notice Return the most recent order IDs a user placed in a market.
    /// @dev Cancelled or filled orders may remain in the list; clients should filter by order existence.
    function getUserOrders(address user, bytes32 marketId) external view returns (bytes32[] memory orderIds);

    /// @notice Start an opening auction for an active empty market.
    /// @dev System-only. The market must be active and have no live open orders.      Historical cleared order ids do not block auction start, but the call      charges gas for scanning those historical ids.
    function startOpeningAuction(bytes32 marketId, uint64 startBlock, uint64 endBlock, uint256 referencePrice) external;

    /// @notice Proposed ordinary-caller bound-session V3 action wrapper.
    /// @dev Inactive until a separately accepted resource policy and dispatch revision.      DXS3 contains the expected principal and current positive generation,      followed by unchanged DXA2 bytes. The result commits the full wrapper.      Sponsorship and relayer adapters are unsupported. Counts retain V2 types.
    /// @param encodedWrapper Canonical complete DXS3 header and unchanged inner batch.
    /// @return resultHash Full-wrapper commitment using the inherited result framing.
    /// @return acceptedCount Accepted action count in inherited uint16 width.
    /// @return rejectedCount Rejected action count in inherited uint16 width.
    function submitBoundSessionActions(bytes calldata encodedWrapper) external returns (bytes32 resultHash, uint16 acceptedCount, uint16 rejectedCount);

    /// @notice Submit one strictly bounded canonical V2 action batch.
    /// @dev The ordinary EVM caller authenticates the batch. The encoded bytes      contain no action-level signature or replay nonce. `resultHash`      commits to the original bytes and every ordered action outcome.
    function submitExchangeActions(bytes calldata encodedActions) external returns (bytes32 resultHash, uint16 acceptedCount, uint16 rejectedCount);

    /// @notice Place a limit order in an active spot market.
    /// @dev Requires an active market, `priceTicks > 0`, `amountLots > 0`, a prior      settlement deposit flag, and enough available collateral. Buy orders      lock quote collateral equal to `priceTicks * amountLots`; sell orders      lock base collateral equal to `amountLots`.
    /// @param marketId Canonical market identifier.
    /// @param side Order side: 0 = Buy, 1 = Sell.
    /// @param priceTicks Limit price in market ticks.
    /// @param amountLots Base quantity in market lots.
    /// @param flags Bit flags from `DiesisOrderFlags`.
    /// @return orderId Canonical order identifier.
    function submitLimitOrder(bytes32 marketId, uint8 side, uint256 priceTicks, uint256 amountLots, uint8 flags) external returns (bytes32 orderId);

    /// @notice Submit a market order intent against the active continuous book.
    /// @dev Requires an active market and `amountLots > 0`. The returned      `filledAmount` is currently zero; economic fills are emitted as      canonical `OrderFilled` events when matching settles.
    /// @param marketId Canonical market identifier.
    /// @param side Order side: 0 = Buy, 1 = Sell.
    /// @param amountLots Base quantity in market lots.
    /// @return filledAmount Reserved fill amount field.
    /// @return orderId Canonical order identifier.
    function submitMarketOrder(bytes32 marketId, uint8 side, uint256 amountLots) external returns (uint256 filledAmount, bytes32 orderId);

    /// @notice Submit a signed request to cancel all active orders in one market.
    /// @dev The payload is a JSON-encoded signed cancel-all spot intent. The      signature binds trader, market, expiry, and replay nonce. The call      scans the trader's historical user-order list for `marketId`, charges      per scanned order, cancels currently active matching orders, and rolls      back nonce consumption if cancellation fails.
    /// @param signedCancelAllJson ABI `bytes` containing UTF-8 JSON for the signed cancel-all payload.
    /// @return cancelled Number of active orders cancelled.
    function submitSignedCancelAllSpotIntent(bytes calldata signedCancelAllJson) external returns (uint256 cancelled);

    /// @notice Submit a signed order or cancel intent.
    /// @dev The payload is a JSON-encoded `SignedIntent`. Order intents may be      submitted by any relayer; the precompile verifies the signature and      uses the signed trader as the effective caller. Trading-key signed      order and cancel intents are constrained by the key's market mask and      notional limit. This ABI intentionally declares no return value because      order and cancel variants have different raw return data. Clients that      need the returned order id should either call direct order methods or      use a low-level call and decode the variant-specific bytes.
    /// @param signedIntentJson ABI `bytes` containing UTF-8 JSON for the signed intent.
    function submitSignedSpotIntent(bytes calldata signedIntentJson) external;

    /// @notice Activate dormant stops triggered by the market's last settled trade.
    /// @dev Permissionless bounded continuation. A buy stop triggers when the      canonical last-trade price rises to or above its trigger price; a sell      stop triggers when it falls to or below. `maxOrders` is clamped to the      protocol activation limit and to the call's gas headroom; the call      never triggers from an oracle, RPC quote, or user-supplied      observation. Each activated stop inserts into the live book and matches      at its limit/protection price (a stop-market executes as an IOC      protected limit) and emits a `StopOrderTriggered` event. A paused      market or a market with no settled trade activates nothing.
    /// @param marketId Canonical market identifier.
    /// @param maxOrders Requested maximum activations this call.
    /// @return activated Number of stops activated.
    /// @return hasMore True when triggerable stops remain past this call's budget.
    function triggerSpotStops(bytes32 marketId, uint16 maxOrders) external returns (uint16 activated, bool hasMore);
}
