// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisPosition {
    struct PositionInfo {
        uint256 debtAmount;
        uint256 lifetimeDelegated;
        uint256 lifetimeRewardsClaimed;
        uint40 lockedUntil;
        uint256[] pendingWithdrawals;
    }

    error ApprovalExpired();

    error ApprovalNotRevokable();

    error BelowMinStake();

    error ExitFeeTooHigh();

    error HasOutstandingDebt();

    error HasOutstandingLockRecords();

    error HasOutstandingShareDebt();

    error HasPendingWithdrawal();

    error InstantExitDisabled();

    error InsufficientCollateral();

    error LockNotExtended(uint40 existingUntil, uint40 requestedUntil);

    error LockNotFound();

    error LockRecordIndexOutOfBounds();

    error LockupTooLong();

    error NativeTransferFailed();

    error NotAuthorized();

    error NotLockManager();

    error NotValidatorShare();

    error PositionLocked();

    error RedeemExceedsShareDebt();

    error RepayExceedsDebt();

    error SamePosition();

    error TokenNotFound();

    error TooManyLockRecords();

    error ValidatorMismatch();

    error ZeroAddress();

    error ZeroLockDuration();

    error ZeroShareAmount();

    event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId);

    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);

    event Delegated(uint256 indexed tokenId, uint32 indexed validator, uint256 stakeAmt);

    event FunctionApprovalRevoked(uint256 indexed tokenId, uint8 indexed fn);

    event FunctionApprovalSet(uint256 indexed tokenId, uint8 indexed fn, address indexed delegatee, uint32 expires);

    event InstantWithdrawExecuted(uint256 indexed tokenId, uint256 withdrawAmount, uint256 fee, address indexed receiver);

    event LiquidTokenMinted(uint256 indexed tokenId, address indexed recipient, uint256 mintAmount);

    event LiquidTokenRepaid(uint256 indexed tokenId, address indexed payer, uint256 burnAmount);

    event LockManagerSet(address indexed manager, bool enabled);

    event LockRemoved(uint256 indexed tokenId, address indexed manager, bytes32 indexed lockId);

    event LockSet(uint256 indexed tokenId, address indexed manager, bytes32 indexed lockId, uint40 lockedUntil);

    event Minted(uint256 indexed tokenId, address indexed owner, uint32 indexed validator);

    event PositionMerged(uint256 indexed fromTokenId, uint256 indexed intoTokenId, uint256 mergedAmount);

    event PositionSplit(uint256 indexed fromTokenId, uint256 indexed newTokenId, uint256 splitAmount);

    event RewardsClaimed(uint256 indexed tokenId, address indexed recipient, uint256 rewardAmt);

    event RewardsRestaked(uint256 indexed tokenId);

    event ShareBackingRedeemed(uint256 indexed fromTokenId, uint256 indexed toTokenId, uint256 amount);

    event SwapDelegated(uint256 indexed fromTokenId, uint256 indexed toTokenId, uint256 swapAmount);

    event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);

    event Undelegated(uint256 indexed tokenId, uint32 indexed validator, uint256 indexed wrId, uint256 stakeAmt);

    event ValidatorExitFeeSet(uint32 indexed validatorId_, uint256 feeBps);

    event ValidatorShareSet(address indexed validatorShare);

    event Withdrawn(uint256 indexed tokenId, uint256 indexed wrId);

    /// @dev Gives permission to `to` to transfer `tokenId` token to another account. The approval is cleared when the token is transferred. Only a single account can be approved at a time, so approving the zero address clears previous approvals. Requirements: - The caller must own the token or be an approved operator. - `tokenId` must exist. Emits an {Approval} event.
    function approve(address to, uint256 tokenId) external;

    /// @dev Returns the number of tokens in ``owner``'s account.
    function balanceOf(address owner) external view returns (uint256 balance);

    function claimRewards(uint256 tokenId, address recipient) external;

    function delegate(uint256 tokenId) external payable;

    /// @notice Return the effective unexpired maximum lock deadline, or zero when unlocked.
    function effectiveLockUntil(uint256 tokenId) external view returns (uint40);

    /// @notice Return the free (unencumbered) collateral: stakedAmount - totalDebt.
    function freeCollateralOf(uint256 tokenId) external view returns (uint256);

    /// @dev Returns the account approved for `tokenId` token. Requirements: - `tokenId` must exist.
    function getApproved(uint256 tokenId) external view returns (address operator);

    /// @notice Whether a new record can be added, or the specified existing record can be extended.
    function hasLockCapacity(uint256 tokenId, address manager, bytes32 lockId) external view returns (bool);

    /// @dev Returns if the `operator` is allowed to manage all of the assets of `owner`. See {setApprovalForAll}
    function isApprovedForAll(address owner, address operator) external view returns (bool);

    function isFunctionApproved(uint256 tokenId, uint8 fn, address caller) external view returns (bool approved);

    /// @notice Create or strictly extend the intrinsic owner lock.
    /// @dev `lockDuration` must be non-zero and must produce a deadline later than the current owner record.
    function lockPosition(uint256 tokenId, uint40 lockDuration) external;

    /// @notice Lock a position on behalf of its owner.
    /// @dev Callable by authorized lock managers. Outstanding records remain enumerable after expiry      until their manager removes them; at most `MAX_LOCK_RECORDS` may exist per position.      A zero duration or a deadline that does not strictly extend the same record reverts.
    function lockPositionFor(uint256 tokenId, bytes32 lockId, uint40 lockDuration) external;

    /// @notice Return one outstanding lock record by index.
    function lockRecordAt(uint256 tokenId, uint256 index) external view returns (address manager, bytes32 lockId, uint40 lockedUntil);

    /// @notice Return the number of bounded outstanding lock records, including expired provenance.
    function lockRecordCount(uint256 tokenId) external view returns (uint256);

    /// @notice Return the deadline recorded for one lock identity.
    function lockUntilFor(uint256 tokenId, address manager, bytes32 lockId) external view returns (uint40);

    /// @notice Atomically merge two positions on the same validator.
    /// @dev Source must have no debt and not be locked. Uses swapDelegate for atomic re-delegation.      Burns the source NFT.
    /// @param fromTokenId The source position (will be burned).
    /// @param intoTokenId The target position (receives the merged stake).
    function mergePosition(uint256 fromTokenId, uint256 intoTokenId) external;

    function mint(uint32 validator) external payable returns (uint256 tokenId);

    function mintLiquidToken(uint256 tokenId, uint256 mintAmount, address recipient) external;

    function mintShareDebt(uint256 tokenId, uint256 shareDebt) external;

    /// @dev Returns the owner of the `tokenId` token. Requirements: - `tokenId` must exist.
    function ownerOf(uint256 tokenId) external view returns (address owner);

    function positionInfo(uint256 tokenId) external view returns (PositionInfo memory info);

    /// @notice Extinguish source share debt and move the same backing stake to a same-validator destination.
    /// @dev Callable only by ValidatorShare. When both token IDs match, only debt is reduced.
    function redeemShareBacking(uint256 fromTokenId, uint256 toTokenId, uint256 shareAmount) external;

    function repayLiquidToken(uint256 tokenId, uint256 burnAmount) external;

    function restakeRewards(uint256 tokenId) external;

    function revokeFunctionApproval(uint256 tokenId, uint8 fn) external;

    /// @dev Safely transfers `tokenId` token from `from` to `to`, checking first that contract recipients are aware of the ERC-721 protocol to prevent tokens from being forever locked. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must exist and be owned by `from`. - If the caller is not `from`, it must have been allowed to move this token by either {approve} or   {setApprovalForAll}. - If `to` refers to a smart contract, it must implement {IERC721Receiver-onERC721Received}, which is called upon   a safe transfer. Emits a {Transfer} event.
    function safeTransferFrom(address from, address to, uint256 tokenId) external;

    /// @dev Safely transfers `tokenId` token from `from` to `to`. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must exist and be owned by `from`. - If the caller is not `from`, it must be approved to move this token by either {approve} or {setApprovalForAll}. - If `to` refers to a smart contract, it must implement {IERC721Receiver-onERC721Received}, which is called upon   a safe transfer. Emits a {Transfer} event.
    function safeTransferFrom(address from, address to, uint256 tokenId, bytes calldata data) external;

    /// @dev Approve or remove `operator` as an operator for the caller. Operators can call {transferFrom} or {safeTransferFrom} for any token owned by the caller. Requirements: - The `operator` cannot be the address zero. Emits an {ApprovalForAll} event.
    function setApprovalForAll(address operator, bool approved) external;

    function setFunctionApproval(uint256 tokenId, uint8 fn, address delegatee, uint32 expires, bool revokable) external;

    /// @notice Return the share debt for a position.
    function shareDebtOf(uint256 tokenId) external view returns (uint256);

    /// @notice Atomically split a position into two on the same validator (no unbonding delay).
    /// @dev Uses swapDelegate for instant re-delegation between positions.
    /// @param fromTokenId The source position to split from.
    /// @param splitAmount Wei to move to the new position (must be ≥ MIN_STAKE and ≤ free collateral;        source remainder must be 0 or ≥ MIN_STAKE).
    /// @return newTokenId The newly minted position NFT.
    function splitPosition(uint256 fromTokenId, uint256 splitAmount) external returns (uint256 newTokenId);

    /// @notice Return the current staked amount for a position (canonical, self-tracked).
    function stakedAmountOf(uint256 tokenId) external view returns (uint256);

    /// @dev Returns true if this contract implements the interface defined by `interfaceId`. See the corresponding https://eips.ethereum.org/EIPS/eip-165#how-interfaces-are-identified[ERC section] to learn more about how these ids are created. This function call must use less than 30 000 gas.
    function supportsInterface(bytes4 interfaceId) external view returns (bool);

    /// @notice Atomically re-delegate stake from one position to another on the same validator.
    /// @dev Called by ValidatorShare for atomic balance swaps. No unbonding delay.
    /// @param fromTokenId Source DiesisPosition token.
    /// @param toTokenId Destination DiesisPosition token.
    /// @param swapAmount Wei to move.
    function swapDelegate(uint256 fromTokenId, uint256 toTokenId, uint256 swapAmount) external;

    /// @notice Return the total debt (LSD + share debt) for a position.
    function totalDebtOf(uint256 tokenId) external view returns (uint256);

    /// @notice Return the total staked amount for a given validator.
    function totalStakedByValidator(uint32 validator) external view returns (uint256);

    /// @dev Transfers `tokenId` token from `from` to `to`. WARNING: Note that the caller is responsible to confirm that the recipient is capable of receiving ERC-721 or else they may be permanently lost. Usage of {safeTransferFrom} prevents loss, though the caller must understand this adds an external call which potentially creates a reentrancy vulnerability. Requirements: - `from` cannot be the zero address. - `to` cannot be the zero address. - `tokenId` token must be owned by `from`. - If the caller is not `from`, it must be approved to move this token by either {approve} or {setApprovalForAll}. Emits a {Transfer} event.
    function transferFrom(address from, address to, uint256 tokenId) external;

    function undelegate(uint256 tokenId, uint256 wrId, uint256 undelegateAmount) external;

    /// @notice Clear one caller-owned lock on a position.
    /// @dev A revoked manager may still clear an exact record it created, but cannot create or extend locks.
    /// @param tokenId The position to unlock.
    /// @param lockId The manager-local lock identifier to remove.
    function unlockPosition(uint256 tokenId, bytes32 lockId) external;

    function validatorOf(uint256 tokenId) external view returns (uint32);

    function withdraw(uint256 tokenId, uint256 wrId) external;

    /// @notice Complete a matured withdrawal and forward the native tokens directly to `recipient`.
    /// @dev The amount is determined by DiesisStaking's stored unstake request; callers cannot         supply a partial amount. `recipient` must be non-zero.
    function withdrawTo(uint256 tokenId, uint256 wrId, address recipient) external;
}
