// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisConductors {
    struct ConductorInfo {
        address conductor;
        uint256 bond;
        uint8 tier;
        uint256 totalEarned;
        uint256 todayEarned;
        uint256 todayCapacityRemainingDs;
        uint64 bondAvailableAfterBlock;
        uint256 pendingRefund;
    }

    event DecreaseFinalized(address indexed conductor, uint256 refunded);

    event DecreaseRequested(address indexed conductor, uint256 amount, uint64 unlockBlock);

    event Registered(address indexed conductor, uint256 added, uint256 newBond, uint8 newTier);

    event ShareEarned(address indexed conductor, uint256 paid, uint256 paidValueDs);

    /// @notice Finalize a previously requested decrease and receive the refund.
    /// @dev Reverts before the unlock block or if no decrease is pending.
    function finalizeDecrease() external;

    /// @notice Read the public conductor record.
    function getConductor(address conductor) external view returns (ConductorInfo memory);

    /// @notice Register a new conductor or top up an existing bond.
    /// @dev `msg.value` is added to the caller's bond. Tier reflects the new total immediately.
    function registerOrTopup() external payable;

    /// @notice Signal intent to decrease bond by `amount`.
    /// @dev Tier is recomputed against the post-decrease bond immediately (spec §5.6).      The refund is redeemable via `finalizeDecrease` after a 7-day timelock.
    function requestDecrease(uint256 amount) external;
}
