// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisSettlementRouter {
    error BalanceDeltaMismatch(uint256 expected, uint256 actual);

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error ReentrancyGuardReentrantCall();

    error SafeERC20FailedOperation(address token);

    error TokenNotAllowed(address token);

    error ZeroAddress();

    error ZeroAmount();

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event RouterDeposit(address indexed payer, address indexed beneficiary, address indexed token, uint256 amount);

    event RouterWithdrawal(address indexed principal, address indexed recipient, address indexed token, uint256 amount);

    event TokenAllowlistUpdated(address indexed token, bool allowed);

    /// @notice Deposit `amount` of `token`, crediting `beneficiary`'s settlement         balance.
    /// @dev Pulls tokens from `msg.sender` into router custody, verifies the      exact received amount, then credits the settlement ledger. A      balance-delta mismatch reverts before any ledger mutation.
    /// @param token The allowlisted ERC-20 token.
    /// @param amount The amount to pull from the caller.
    /// @param beneficiary The settlement account to credit.
    /// @return credited The exact amount credited (always equals `amount`).
    function deposit(address token, uint256 amount, address beneficiary) external returns (uint256 credited);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    /// @notice Add or remove a token from the standard-collateral allowlist.
    /// @dev PRECONDITION: governance MUST only admit a token that is standard      ERC-20, exact-balance-accounted, and neither fee-on-transfer nor      rebasing (no supply-elastic or balance-mutating hooks). The router's      single-transaction delta checks catch synchronous fee/rebase      behavior, but an asynchronously rebasing token can still render      pooled custody insolvent; admitting one is a governance error that      only the vetting at admission time can prevent.
    /// @param token The ERC-20 token address.
    /// @param allowed Whether the token may be deposited and withdrawn.
    function setTokenAllowed(address token, bool allowed) external;

    /// @notice Canonical settlement precompile the router drives. Set once at         construction (or genesis seed); there is no setter.
    function settlement() external view returns (address);

    /// @notice Governance-controlled allowlist of standard ERC-20 collateral.
    function tokenAllowed(address) external view returns (bool);

    /// @notice Aggregate outstanding settlement liability the router custodies         per token: the sum of every credited deposit minus every         withdrawal. For a compliant token the invariant         `token.balanceOf(address(this)) >= totalCustodied[token]` holds at         all times; a violation indicates an asynchronous rebase that the         allowlist should have excluded.
    function totalCustodied(address) external view returns (uint256);

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    /// @notice Withdraw `amount` of `token` from the caller's settlement balance         to `recipient`.
    /// @dev Debits the settlement ledger and the aggregate liability first, then      releases custody. A failed token transfer reverts both mutations      atomically. Verifies the exact released amount against BOTH the      router's balance delta and the recipient's balance delta: the      recipient-delta check rejects outbound fee-on-transfer tokens that      would deliver less than the debited amount. An asynchronous shortfall      in pooled custody makes the releasing transfer revert on insufficient      balance, so the withdrawal fails closed for the affected caller      rather than corrupting other users' balances.
    /// @param token The allowlisted ERC-20 token.
    /// @param amount The amount to debit and release.
    /// @param recipient The address that receives the released tokens.
    function withdraw(address token, uint256 amount, address recipient) external;
}
