// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisBaseRegistrar {
    error CommitmentMissing();

    error CommitmentTooNew();

    error CommitmentTooOld();

    error CommitmentUsed();

    error DurationOutOfRange();

    error InsufficientPayment();

    error InvalidLabel();

    error NameUnavailable();

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error RecordsHashMismatch();

    error ReservedLabel();

    error ResolverCallFailed();

    error ReverseRecordUnauthorized();

    event FeeSplitUpdated(uint256 burnShare, uint256 treasuryShare, uint256 maintenanceShare);

    event NameCommitted(bytes32 indexed commitment, uint64 timestamp);

    event NameRegistered(bytes32 indexed labelhash, bytes32 indexed node, string label, address indexed owner, uint64 expiry);

    event NameRenewed(bytes32 indexed labelhash, string label, uint64 expiry, uint256 price);

    event NameReserved(bytes32 indexed labelhash, string label, bool reserved);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event PricingUpdated(uint256 threeCharYearPrice, uint256 fourCharYearPrice, uint256 defaultYearPrice, uint256 startPremium);

    event RentPaid(bytes32 indexed labelhash, uint256 amount, uint256 burnAmount, uint256 treasuryAmount, uint256 maintenanceAmount);

    event ReverseRegistrarChanged(address indexed reverseRegistrar);

    event TimingUpdated(uint256 minCommitmentAge, uint256 maxCommitmentAge, uint256 minRegistrationDuration, uint256 maxRegistrationDuration, uint256 gracePeriod, uint256 premiumPeriod);

    function DEFAULT_YEAR_PRICE() external view returns (uint256);

    function DS_NODE() external view returns (bytes32);

    function FOUR_CHAR_YEAR_PRICE() external view returns (uint256);

    function GRACE_PERIOD() external view returns (uint64);

    function MAX_COMMITMENT_AGE() external view returns (uint64);

    function MAX_REGISTRATION_DURATION() external view returns (uint64);

    function MIN_COMMITMENT_AGE() external view returns (uint64);

    function MIN_REGISTRATION_DURATION() external view returns (uint64);

    function PREMIUM_PERIOD() external view returns (uint64);

    function START_PREMIUM() external view returns (uint256);

    function THREE_CHAR_YEAR_PRICE() external view returns (uint256);

    function available(string calldata label) external view returns (bool);

    function burnShare() external view returns (uint256);

    function burnSink() external view returns (address);

    function commit(bytes32 commitment) external;

    function commitmentAge(bytes32 commitment) external view returns (uint256);

    function commitments(bytes32 commitment) external view returns (uint64 timestamp);

    function currentPremium(string calldata label) external view returns (uint256);

    function defaultYearPrice() external view returns (uint256);

    function fourCharYearPrice() external view returns (uint256);

    function gracePeriod() external view returns (uint256);

    function maintenance() external view returns (address);

    function maintenanceShare() external view returns (uint256);

    function makeCommitment(string calldata label, address owner_, address resolver_, bytes32 recordsHash, uint64 duration, bytes32 secret, bool reverseRecord, uint256 nonce) external pure returns (bytes32);

    function maxCommitmentAge() external view returns (uint256);

    function maxRegistrationDuration() external view returns (uint256);

    function minCommitmentAge() external view returns (uint256);

    function minRegistrationDuration() external view returns (uint256);

    function nameExpires(bytes32 labelhash) external view returns (uint64 expiry);

    function normalizeLabel(string calldata label) external pure returns (string memory normalized);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    function premiumPeriod() external view returns (uint256);

    function register(string calldata label, address owner_, address resolver_, uint64 duration, bytes32 secret, bool reverseRecord, uint256 nonce, bytes[] calldata resolverCalls) external payable returns (bytes32 node);

    function registry() external view returns (address);

    function renew(string calldata label, uint64 duration) external payable returns (uint64 expiry);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    function rentPrice(string calldata label, uint64 duration) external view returns (uint256);

    function reservedLabels(bytes32 labelhash) external view returns (bool reserved);

    function reverseRegistrar() external view returns (address);

    function setFeeSplit(uint256 burnShare_, uint256 treasuryShare_, uint256 maintenanceShare_) external;

    function setPricing(uint256 threeCharYearPrice_, uint256 fourCharYearPrice_, uint256 defaultYearPrice_, uint256 startPremium_) external;

    function setReservedLabel(string calldata label, bool reserved) external;

    function setReverseRegistrar(address reverseRegistrar_) external;

    function setTiming(uint256 minCommitmentAge_, uint256 maxCommitmentAge_, uint256 minRegistrationDuration_, uint256 maxRegistrationDuration_, uint256 gracePeriod_, uint256 premiumPeriod_) external;

    function startPremium() external view returns (uint256);

    function threeCharYearPrice() external view returns (uint256);

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    function treasury() external view returns (address);

    function treasuryShare() external view returns (uint256);

    function usedCommitments(bytes32 commitment) external view returns (bool used);
}
