// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisNameRegistry {
    error NotAuthorized();

    error ZeroOwner();

    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);

    event ControllerChanged(address indexed controller, bool approved);

    event ExpiryChanged(bytes32 indexed node, uint64 expiry);

    event NamePolicyChanged(address indexed policy);

    event OwnerChanged(bytes32 indexed node, address indexed owner);

    event ResolverChanged(bytes32 indexed node, address indexed resolver);

    event TTLChanged(bytes32 indexed node, uint64 ttl);

    function controllers(address controller) external view returns (bool);

    function expiry(bytes32 node) external view returns (uint64);

    function isApprovedForAll(address owner_, address operator) external view returns (bool);

    function isAuthorized(bytes32 node, address actor) external view returns (bool);

    function isExpired(bytes32 node) external view returns (bool);

    function namePolicy() external view returns (address);

    function owner(bytes32 node) external view returns (address);

    function ownershipEpoch(bytes32 node) external view returns (uint256);

    function resolver(bytes32 node) external view returns (address);

    function setApprovalForAll(address operator, bool approved) external;

    function setController(address controller, bool approved) external;

    function setExpiry(bytes32 node, uint64 expiry_) external;

    function setNamePolicy(address policy) external;

    function setOwner(bytes32 node, address owner_) external;

    function setResolver(bytes32 node, address resolver_) external;

    function setSubnodeOwner(bytes32 node, bytes32 label, address owner_) external returns (bytes32);

    function setSubnodeRecord(bytes32 node, bytes32 label, address owner_, address resolver_, uint64 ttl_, uint64 expiry_) external returns (bytes32);

    function setTTL(bytes32 node, uint64 ttl_) external;

    function ttl(bytes32 node) external view returns (uint64);
}
