// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisPerpsBook {
    struct PackedPosition {
        bytes32 header;
        uint256 size;
        uint256 entryPrice;
    }

    event ExchangeActionAccepted(bytes16 indexed clientActionId, uint16 indexed actionIndex, uint8 actionTag, bytes32 indexed marketId, address principal, bytes32 resultId);

    event ExchangeActionRejected(bytes16 indexed clientActionId, uint16 indexed actionIndex, uint8 actionTag, bytes32 indexed marketId, address principal, uint16 reasonCode, bytes32 context);

    event ExchangeL3Mutation(bytes32 indexed marketId, bytes32 indexed orderId, address indexed trader, uint8 mutation, uint8 side, uint64 priceTicks, uint64 quantityLots, uint64 remainingLots);

    event FundingApplied(bytes32 indexed marketId, int256 fundingRate, uint64 timestamp);

    event IsolatedMarginAdjusted(bytes32 indexed marketId, address indexed trader, int256 marginDelta, uint256 newIsolatedMargin);

    event MarkPriceUpdated(bytes32 indexed marketId, uint256 price, uint256 timestamp);

    event OrderCancelled(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader);

    event OrderFilled(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader, uint256 fillQty, uint256 fillPrice, uint256 remainingAmount, bool complete);

    event OrderPlaced(bytes32 indexed orderId, bytes32 indexed marketId, address indexed trader, uint8 side, uint256 price, uint256 amount, uint8 flags);

    event PositionClosed(bytes32 indexed marketId, address indexed trader, int256 realizedPnl);

    event PositionCollateralAdjusted(bytes32 indexed marketId, address indexed trader, int256 collateralDelta, uint256 newClaim);

    /// @notice Add or remove isolated margin on the caller's position.
    /// @dev A positive `marginDelta` locks quote collateral from the caller's      available settlement balance into the position's isolated margin; a      negative one releases it. Reductions are consensus-guarded and revert      when they would leave the position below maintenance margin. Emits      {IsolatedMarginAdjusted}.
    /// @param marketId The market whose position is adjusted.
    /// @param marginDelta Quote-denominated signed adjustment.
    function adjustIsolatedMargin(bytes32 marketId, int256 marginDelta) external;

    /// @notice Request the system-owned canonical priced runtime tick.
    /// @dev Inactive until qualified runtime activation. Every caller currently reverts.      Future execution requires authenticated selected authority and a matching policy hash.
    /// @param policyHash Commitment of the authenticated execution policy.
    function advancePricedPerpRuntime(bytes32 policyHash) external;

    /// @notice Atomically cancel and replace an order with new price, amount,         expiry, canonical margin reservation, and priority identity.
    function amendPerpOrder(bytes32 orderId, uint256 price, uint256 amount, uint64 expiry) external returns (bytes32 replacementOrderId);

    /// @notice Advance canonical funding through solvency-frontier segments.
    /// @dev System-only and bounded to the protocol funding-rate limit.
    function applyPerpFunding(bytes32 marketId, int256 fundingRateBps) external;

    /// @notice Cancel an owned V1 order and return all unused canonical margin.
    function cancelPerpOrder(bytes32 orderId) external;

    /// @notice Commit one system-owned opposite-side fill through canonical clearing.
    /// @dev Reads and validates both stored V1 orders, derives deterministic      maker/taker fees and persistent frontier proofs, then commits the      PreparedClearingTransactionV1 and both order consumptions under one      outer EVM checkpoint. The lower order ID is the canonical maker.
    function executePerpTrade(bytes32 makerOrderId, bytes32 takerOrderId, uint256 fillPrice, uint256 fillQty) external returns (bytes32 clearingTransactionId);

    /// @notice Permissionlessly expire a GTD order after its canonical deadline.
    function expirePerpOrder(bytes32 orderId) external;

    /// @notice Finalize the exact stored snapshot of one closed fee epoch.
    /// @dev Native queue/accounting behavior is introduced by X4b M3. This      declaration prevents public ABI drift before that implementation.
    function finalizePerpFeeEpoch(bytes32 marketId, uint64 epoch, bytes32 snapshotHash) external;

    /// @notice Read one trader's quote-denominated isolated margin for a market.
    function getIsolatedMargin(address trader, bytes32 marketId) external view returns (uint256 isolatedMargin);

    /// @notice Read one trader's canonical perpetual position for a market.
    function getPosition(address trader, bytes32 marketId) external view returns (PackedPosition memory position);

    /// @notice Proposed ordinary-caller bound-session V3 action wrapper.
    /// @dev Inactive until a separately accepted resource policy and dispatch revision.      DXS3 contains the expected principal and current positive generation,      followed by unchanged DXA2 bytes. The result commits the full wrapper.      Sponsorship and relayer adapters are unsupported. Counts retain V2 types.
    /// @param encodedWrapper Canonical complete DXS3 header and unchanged inner batch.
    /// @return resultHash Full-wrapper commitment using the inherited result framing.
    /// @return acceptedCount Accepted action count in inherited uint16 width.
    /// @return rejectedCount Rejected action count in inherited uint16 width.
    function submitBoundSessionActions(bytes calldata encodedWrapper) external returns (bytes32 resultHash, uint16 acceptedCount, uint16 rejectedCount);

    /// @notice Encode the shared bounded V2 action call for future Lane B use.
    /// @dev The ABI is frozen for tooling parity, but perpetual V2 execution      remains protocol-gated until the Lane B activation revision.      `resultHash` commits to the original bytes and every ordered action outcome.
    function submitExchangeActions(bytes calldata encodedActions) external returns (bytes32 resultHash, uint16 acceptedCount, uint16 rejectedCount);

    /// @notice Submit one versioned perpetual order funded from canonical settlement custody.
    /// @dev The call atomically moves initial margin plus the deterministic fee      reserve from GlobalUserAvailable to the market's UserMargin ledger.      `price` is a nonzero integer tick and price-protected market orders      use it as their worst acceptable execution price. `expiry == 0`      selects GTC; otherwise expiry is a Unix timestamp in seconds.      V1 requires `flags == 0`; reduce-only and advanced time-in-force      semantics are reserved for the bounded V2 action surface.
    function submitPerpOrder(bytes32 marketId, uint8 side, uint8 orderType, uint256 price, uint256 amount, uint8 flags, uint8 marginType, uint64 expiry) external returns (bytes32 orderId);

    /// @notice Execute a sponsored bounded V2 action batch on behalf of a signer.
    /// @dev The relayer is the outer transaction sender and pays fees; the      recovered EIP-712 signer of `signedEnvelope` is the trading      principal. The precompile verifies the signature, consumes the      signer's canonical per-trader nonce-bitmap bit, and executes the      exact same canonical action bytes, admission policy, replay      protection, clearing journal, and logs as the direct      `submitExchangeActions` path. Later tasks implement verification      and execution; this freezes the release selector and wire shape.
    /// @param signedEnvelope ABI `bytes` containing the canonical signed        perpetual-actions envelope.
    /// @return batchId Canonical identifier committing to the executed batch.
    function submitSponsoredPerpActions(bytes calldata signedEnvelope) external returns (bytes32 batchId);

    /// @notice Advance the canonical scaled mark through solvency-frontier segments.
    /// @dev System-only. If a root is reached, the market enters Protection and      persists the original target until liquidation resolves the root.
    function updatePerpMark(bytes32 marketId, uint256 markPrice) external;

    /// @notice Persist one validator-attested oracle round for a market.
    /// @dev System-only. Accepts strictly increasing rounds and observed-at      timestamps, an active `sourceSetHash`, and a canonical `evidenceHash`      commitment. The call atomically writes the canonical index/mark,      round, observed-at, source-set/evidence commitments, and derived      circuit-breaker/recovery state; there is no operator path that      bypasses freshness or evidence. Later tasks implement the transition;      this freezes the release selector and argument layout.
    /// @param marketId Canonical market identifier.
    /// @param indexPrice Attested index price.
    /// @param markPrice Attested canonical mark price.
    /// @param observedAt Canonical observed-at timestamp in seconds.
    /// @param oracleRound Monotonic oracle round.
    /// @param sourceSetHash Commitment to the active source set.
    /// @param evidenceHash Commitment to the ordered aggregation evidence.
    function updatePerpOracle(bytes32 marketId, uint256 indexPrice, uint256 markPrice, uint64 observedAt, uint64 oracleRound, bytes32 sourceSetHash, bytes32 evidenceHash) external;

    /// @notice Persist one descriptor-authorized priced oracle observation.
    /// @dev System-only, caller address zero. payload is exactly one canonical      DOR2 observation: a 128-byte V2 context/round header followed by a      144-byte observation. The native runtime verifies chain, genesis,      exact parent number/hash, immutable descriptor/source commitments,      tick alignment and canonical observation freshness before writes.      Canonical oracle prices use p; the clearing mirror uses p*PRICE_SCALE.      This distinct selector returns no data and leaves V1 encoding intact.
    function updatePricedOracle(bytes calldata payload) external;
}
