// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisConfig {
    error OutOfRange();

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error SumExceedsOne();

    event DelegationFanoutLimitUpdated(uint256 value);

    event ExitDelayCheckpointsUpdated(uint256 value);

    event ExitDelaySecondsUpdated(uint256 value);

    event LivenessDowntimeLimitUpdated(uint256 value);

    event LivenessMissedBlockLimitUpdated(uint256 value);

    event MintReceiverUpdated(address indexed value);

    event NetworkBurnCutUpdated(uint256 value);

    event OperatorTakeRateUpdated(uint256 value);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event ReliabilityFloorUpdated(uint64 value);

    event ReliabilitySampleCheckpointsUpdated(uint32 value);

    event RewardStreamPerSecondUpdated(uint256 value);

    event SurplusRewardBurnCutUpdated(uint256 value);

    event TreasuryCutUpdated(uint256 value);

    event ValidatorBondFloorUpdated(uint256 value);

    function CUT_RATE_UPPER() external view returns (uint256);

    function DEFAULT_DELEGATION_FANOUT_LIMIT() external view returns (uint256);

    function DEFAULT_EXIT_DELAY_CHECKPOINTS() external view returns (uint256);

    function DEFAULT_EXIT_DELAY_SECONDS() external view returns (uint256);

    function DEFAULT_LIVENESS_DOWNTIME_LIMIT() external view returns (uint256);

    function DEFAULT_LIVENESS_MISSED_BLOCK_LIMIT() external view returns (uint256);

    function DEFAULT_NETWORK_BURN_CUT() external view returns (uint256);

    function DEFAULT_OPERATOR_TAKE_RATE() external view returns (uint256);

    function DEFAULT_RELIABILITY_FLOOR() external view returns (uint64);

    function DEFAULT_RELIABILITY_SAMPLE_CHECKPOINTS() external view returns (uint32);

    function DEFAULT_REWARD_STREAM_PER_SECOND() external view returns (uint256);

    function DEFAULT_SURPLUS_REWARD_BURN_CUT() external view returns (uint256);

    function DEFAULT_TREASURY_CUT() external view returns (uint256);

    function DEFAULT_VALIDATOR_BOND_FLOOR() external view returns (uint256);

    function DELEGATION_FANOUT_LIMIT_LOWER() external view returns (uint256);

    function DELEGATION_FANOUT_LIMIT_UPPER() external view returns (uint256);

    function EXIT_DELAY_CHECKPOINTS_LOWER() external view returns (uint256);

    function EXIT_DELAY_CHECKPOINTS_UPPER() external view returns (uint256);

    function EXIT_DELAY_SECONDS_LOWER() external view returns (uint256);

    function EXIT_DELAY_SECONDS_UPPER() external view returns (uint256);

    function LIVENESS_DOWNTIME_LIMIT_LOWER() external view returns (uint256);

    function LIVENESS_DOWNTIME_LIMIT_UPPER() external view returns (uint256);

    function LIVENESS_MISSED_BLOCK_LIMIT_LOWER() external view returns (uint256);

    function LIVENESS_MISSED_BLOCK_LIMIT_UPPER() external view returns (uint256);

    function OPERATOR_TAKE_RATE_UPPER() external view returns (uint256);

    function RELIABILITY_FLOOR_UPPER() external view returns (uint64);

    function RELIABILITY_SAMPLE_LOWER() external view returns (uint32);

    function RELIABILITY_SAMPLE_UPPER() external view returns (uint32);

    function REWARD_STREAM_PER_SECOND_UPPER() external view returns (uint256);

    function SURPLUS_REWARD_BURN_CUT_UPPER() external view returns (uint256);

    function VALIDATOR_BOND_FLOOR_LOWER() external view returns (uint256);

    function VALIDATOR_BOND_FLOOR_UPPER() external view returns (uint256);

    /// @notice Maximum delegated stake as a multiple of the operator bond [1-24x]
    function delegationFanoutLimit() external view returns (uint256);

    /// @notice Minimum checkpoints before an unstake request can be withdrawn [2-100]
    function exitDelayCheckpoints() external view returns (uint256);

    /// @notice Minimum seconds before an unstake request can be withdrawn [14d-30d]
    function exitDelaySeconds() external view returns (uint256);

    /// @notice Seconds offline that triggers offline penalty [1-10 days]
    function livenessDowntimeLimit() external view returns (uint256);

    /// @notice Number of missed blocks that triggers offline penalty [100-1M]
    function livenessMissedBlockLimit() external view returns (uint256);

    /// @notice Address that receives newly issued (minted) tokens
    function mintReceiver() external view returns (address);

    /// @notice Fraction of tx fees burned each checkpoint [0-100%]
    function networkBurnCut() external view returns (uint256);

    /// @notice Default operator reward cut as a fraction [0-20%]
    function operatorTakeRate() external view returns (uint256);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    /// @notice Minimum rolling-average uptime before PERFORMANCE_FAULT deactivation [0-90%]
    function reliabilityFloor() external view returns (uint64);

    /// @notice Number of checkpoints in the rolling average uptime window [10-87,600]
    function reliabilitySampleCheckpoints() external view returns (uint32);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    /// @notice Base staking reward per second in tokens [0-0.27 tokens/sec]
    function rewardStreamPerSecond() external view returns (uint256);

    function setDelegationFanoutLimit(uint256 v) external;

    function setExitDelayCheckpoints(uint256 v) external;

    function setExitDelaySeconds(uint256 v) external;

    function setLivenessDowntimeLimit(uint256 v) external;

    function setLivenessMissedBlockLimit(uint256 v) external;

    function setMintReceiver(address v) external;

    function setNetworkBurnCut(uint256 v) external;

    function setOperatorTakeRate(uint256 v) external;

    function setReliabilityFloor(uint64 v) external;

    function setReliabilitySampleCheckpoints(uint32 v) external;

    function setRewardStreamPerSecond(uint256 v) external;

    function setSurplusRewardBurnCut(uint256 v) external;

    function setTreasuryCut(uint256 v) external;

    function setValidatorBondFloor(uint256 v) external;

    /// @notice Fraction of extra reward allocations that are burned [0-100%]
    function surplusRewardBurnCut() external view returns (uint256);

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    /// @notice Fraction of tx fees sent to treasury each checkpoint [0-100%]; networkBurnCut + treasuryCut ≤ 100%
    function treasuryCut() external view returns (uint256);

    /// @notice Minimum operator bond required to register a validator [125K-8.5M tokens]
    function validatorBondFloor() external view returns (uint256);
}
