// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisCoreVault {
    struct ExitRequest {
        address depositor;
        uint128 sharesBurned;
        uint64 requestedBlock;
        uint64 pricedNavBlock;
        uint256 pricedSharePriceQ96;
    }

    struct NavCheckpoint {
        uint64 blockNumber;
        uint256 totalAssets;
        uint128 totalShares;
        uint256 sharePriceQ96;
    }

    struct StrategyRiskParams {
        uint256 maxNotionalPerMarket;
        uint16 maxLeverage;
        uint16 maxSingleFillSlippageBps;
        uint16 adlCallRatioBps;
        uint16 insuranceCallCapBpsOfTvl;
        uint16 maxPositionConcentrationBps;
        uint8 liquidationEngineMode;
    }

    struct PauseState {
        bool paused;
        uint64 lastPauseBlock;
        uint64 expiresAtBlock;
    }

    event Deposited(uint8 indexed id, address indexed depositor, uint256 amount, uint128 sharesMinted);

    event ExitCancelled(uint8 indexed id, address indexed depositor, uint256 queueIndex);

    event ExitProcessed(uint8 indexed id, address indexed depositor, uint256 assetsReturned, uint128 sharesBurned);

    event ExitRequested(uint8 indexed id, address indexed depositor, uint128 sharesBurned, uint64 pricedNavBlock);

    event RiskParamChangeExecuted(uint8 indexed id);

    event RiskParamChangeProposed(uint8 indexed id, uint64 unlockBlock);

    event StrategyPaused(uint8 indexed id, uint64 expiresAtBlock);

    /// @notice Cancel a previously queued exit at `queueIndex` in the         FIFO list. Returns the locked shares to the caller. Only         the owner of the request may cancel.
    function cancelExit(uint8 id, uint256 queueIndex) external;

    /// @notice Deposit `amount` of the strategy's quote asset and mint         proportional shares. Reverts if the strategy is paused.
    /// @dev `msg.value` semantics depend on the precompile's chosen      payment routing; the canonical implementation accepts native      DS for DS-denominated sub-vaults and bridges for others.
    function deposit(uint8 id, uint256 amount) external payable;

    /// @notice Execute a previously proposed risk-parameter change once         the timelock has elapsed. Anyone can call.
    function executeRiskParamChange(uint8 id) external;

    /// @notice Snapshot of the queued exits for a strategy, in FIFO order.
    function exitQueue(uint8 id) external view returns (ExitRequest[] memory);

    /// @notice Get the NAV checkpoint stored at `blockNumber`, if any.
    /// @return cp The checkpoint; `cp.blockNumber == 0` indicates no         checkpoint exists at that block.
    function getCheckpoint(uint8 id, uint64 blockNumber) external view returns (NavCheckpoint memory cp);

    /// @notice Read the currently pre-committed risk parameters.
    function getRiskParams(uint8 id) external view returns (StrategyRiskParams memory);

    /// @notice Current pause record for a strategy.
    function pauseState(uint8 id) external view returns (PauseState memory);

    /// @notice Pause the strategy (deny-only). Subject to a 30-day         cooldown and auto-expiry after 7 days. The pause can         deny new deposits and exit requests; it CANNOT move         funds, reverse trades, change risk params, or alter         NAV checkpoints.
    function pauseStrategy(uint8 id) external;

    /// @notice Propose a new risk-parameter set for the strategy. The         change unlocks after a 7-day timelock; anyone can call         `executeRiskParamChange` afterwards. There is NO         override path.
    function proposeRiskParamChange(uint8 id, StrategyRiskParams calldata newParams) external;

    /// @notice Queue an exit request. The request is priced against the         NAV checkpoint at `block.number - 1`. Reverts if the         strategy is paused, the queue is full, or the caller does         not hold the requested shares.
    function requestExit(uint8 id, uint128 shares) external;

    /// @notice Per-depositor share balance.
    function shareBalance(uint8 id, address depositor) external view returns (uint128);

    /// @notice Total assets currently held by the sub-vault.
    function totalAssets(uint8 id) external view returns (uint256);

    /// @notice Outstanding share supply for the sub-vault.
    function totalShares(uint8 id) external view returns (uint128);
}
