// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisPatron {
    struct CampaignVoucherV1 {
        bytes32 campaignId;
        address beneficiary;
        address target;
        bytes4 selector;
        uint32 maxTransactions;
        uint256 maxLifetimeSpend;
        uint64 expiry;
        uint256 nonce;
    }

    struct GrantInfo {
        uint256 balance;
        uint256 totalContributed;
        uint256 totalSpent;
    }

    struct PendingReservationV2 {
        bytes32 grantId;
        address beneficiary;
        uint256 maximumFee;
    }

    struct ReservationExitSettlementV1 {
        bytes32 grantId;
        uint256 totalRefund;
        uint256 totalDetachedShares;
        uint256 remainingDetachedShares;
        uint256 remainingEscrow;
    }

    struct ReservationExitSnapshotV1 {
        uint256 detachedShares;
        bool claimed;
        bool snapshotted;
    }

    error ActiveReservationLimitReached();

    error BurnFlushActive();

    error CampaignAlreadyFunded();

    error CampaignAlreadyRegistered();

    error CampaignIsRevoked();

    error CampaignJarUnfunded();

    error CampaignNotRegistered();

    error ContractPaused();

    error ECDSAInvalidSignature();

    error ECDSAInvalidSignatureLength(uint256 length);

    error ECDSAInvalidSignatureS(bytes32 s);

    error FeeExceedsReservation();

    error IncompleteReservationExit();

    error InvalidAccrualBlock();

    error InvalidAddress();

    error InvalidAuthorization();

    error InvalidGrantId();

    error InvalidReservationId();

    error InvalidVoucher();

    error InvalidVoucherSignature();

    error NativeTransferFailed();

    error NoGrantShare();

    error NoPendingReservation();

    error NoReservationExitClaim();

    error OwnableInvalidOwner(address owner);

    error OwnableUnauthorizedAccount(address account);

    error ReservationActive();

    error ReservationGenerationMismatch();

    error UnattributedNativeTransfer();

    error Unauthorized();

    error VoucherAlreadyUsed();

    error VoucherExpired();

    event AccountGrantAssigned(address indexed account, bytes32 indexed grantId);

    event BurnFlushFailed(address indexed staking, uint256 amount);

    event BurnFlushed(address indexed staking, uint256 amount);

    event CampaignOwnerRotated(bytes32 indexed campaignId, address indexed previousOwner, address indexed newOwner);

    event CampaignRegistered(bytes32 indexed campaignId, address indexed owner);

    event CampaignRevocationSet(bytes32 indexed campaignId, bool revoked);

    event CampaignVoucherClaimed(bytes32 indexed campaignId, address indexed beneficiary, uint256 nonce, bytes32 grantId);

    event CampaignVoucherRevoked(bytes32 indexed campaignId, address indexed beneficiary, uint256 nonce);

    event GrantAuthorizationRevoked(address indexed beneficiary, bytes32 indexed grantId);

    event GrantAuthorizationSet(address indexed beneficiary, bytes32 indexed grantId, address indexed target, bytes4 selector, uint32 maxTransactions, uint256 maxLifetimeSpend, uint64 expiry);

    event GrantContributed(bytes32 indexed grantId, address indexed contributor, uint256 amount);

    event GrantGasLimitsUpdated(uint256 reserveGas, uint256 settleGas);

    event GrantReservationCancelled(bytes32 indexed reservationId, bytes32 indexed grantId, address beneficiary, uint256 maximumFee);

    event GrantReserved(bytes32 indexed reservationId, bytes32 indexed grantId, address indexed beneficiary, uint256 maximumFee);

    event GrantSettled(bytes32 indexed reservationId, bytes32 indexed grantId, address beneficiary, uint256 actualFee, uint256 refundedFee);

    event GrantWithdrawn(bytes32 indexed grantId, address indexed contributor, uint256 amount);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event Paused(bool paused);

    event ReferralGrantSet(address indexed referrer, address indexed referred, bytes32 grantId);

    event ReservationExitSnapshotted(bytes32 indexed reservationId, bytes32 indexed grantId, address indexed contributor, uint64 contributionGeneration, uint256 claimShares);

    event ReservationExitWithdrawn(bytes32 indexed reservationId, bytes32 indexed grantId, address indexed contributor, uint256 amount);

    event SettledBurnAccrued(uint64 indexed blockNumber, uint256 totalActualFee);

    event StakingAddressUpdated(address indexed newAddress);

    /// @notice Accrue the block's total settled Patron fees into the burn accumulator exactly once, before block finalization.
    /// @dev The Rust executor sums the actual fees it settled in this block and dispatches one system call. Requiring `blockNumber == block.number` and `blockNumber > lastAccruedBlock` makes double accrual unrepresentable, while canonical reorg rollback restores the prior latch and accumulator.
    function accrueSettledBurnV2(uint64 blockNumber, uint256 totalActualFee) external;

    /// @notice Settled fees waiting for a best-effort burn outside consensus settlement. Updated once per block by the system-authorized `accrueSettledBurnV2`.
    function accruedBurn() external view returns (uint256);

    /// @notice Assign a funded grant jar to a specific account.
    /// @dev Use `bytes32(0)` to clear an assignment.
    function assignAccountGrant(address account, bytes32 grantId) external;

    /// @notice Deterministic, owner-bound campaign id for a `(owner, salt)` pair.
    /// @dev Binding the owner into the id means only that owner can register it, so a front-running registration cannot capture a victim's planned campaign.
    function campaignIdFor(address owner, bytes32 salt) external pure returns (bytes32);

    /// @notice Current owner of a campaign, or zero if unregistered.
    function campaignOwner(bytes32 campaignId) external view returns (address);

    /// @notice Whether a campaign is revoked and refusing new claims.
    function campaignRevoked(bytes32 campaignId) external view returns (bool);

    /// @notice EIP-712 digest a campaign owner signs to authorize a voucher. Bound to this chain and Patron address so a signature cannot be replayed across chains or a redeployed contract.
    function campaignVoucherDigest(CampaignVoucherV1 calldata voucher) external view returns (bytes32);

    /// @notice Whether one (beneficiary, nonce) voucher has been claimed or revoked.
    function campaignVoucherUsed(bytes32 campaignId, address beneficiary, uint256 nonce) external view returns (bool);

    /// @notice Reverse one reservation after pre-commit execution failure.
    function cancelGrantV2(bytes32 reservationId) external;

    /// @notice Claim a signed campaign voucher, atomically assigning the campaign jar to the beneficiary and installing the exact bounded authorization.
    /// @dev Callable only by the voucher's beneficiary. A bootstrap reserve for this same claim transaction may already have consumed the fresh authorization's first transaction and provisional spend, so the voucher bounds are held to at least what is already consumed and the counters are preserved: the claim transaction itself is the first sponsored draw.
    function claimCampaignVoucherV1(CampaignVoucherV1 calldata voucher, bytes calldata signature) external;

    /// @notice Deposit native tokens into a grant identified by `grantId`.
    function contribute(bytes32 grantId) external payable;

    /// @notice Best-effort burn of all settled fees. Anyone may retry after a staking outage; failure restores the accrual and never reverts settlement.
    function flushBurn() external returns (bool success);

    /// @notice Beneficiary → grantId → exact route and bounded lifetime authorization.
    function grantAuthorizations(address, bytes32) external view returns (address target, bytes4 selector, uint64 expiry, uint32 maxTransactions, uint32 transactionsUsed, uint256 maxLifetimeSpend, uint256 lifetimeSpent);

    /// @notice Return gas limits reserved for patronage overhead.
    function grantGasOverhead() external view returns (uint256 reserveGas, uint256 settleGas, uint256 totalOverhead);

    /// @notice Account-specific jar for one onboarding account.
    function grantIdForAccount(address account) external pure returns (bytes32 result);

    /// @notice Campaign jar for partner or community onboarding programs.
    function grantIdForCampaign(bytes32 campaignId) external pure returns (bytes32 result);

    /// @notice Referral encore jar for one referrer/referred pair.
    function grantIdForReferral(address referrer, address referred) external pure returns (bytes32 result);

    /// @notice Shared welcome jar for the first few transactions from new accounts.
    function grantIdForWelcome() external pure returns (bytes32 result);

    function grantInfo(bytes32 grantId) external view returns (GrantInfo memory info);

    /// @notice grantId → public grant accounting
    function grants(bytes32) external view returns (uint256 balance, uint256 totalContributed, uint256 totalSpent);

    /// @notice Highest block number whose settled fees have been accrued to `accruedBurn`. The strictly-increasing latch makes duplicate accrual unrepresentable and is restored to its prior value by canonical reorg rollback.
    function lastAccruedBlock() external view returns (uint64);

    /// @notice Bounded by the published reserve overhead: an exit walks every active reservation and each reservation's earlier active predecessors.
    function maxActiveReservationsPerGrant() external view returns (uint256);

    /// @notice Native-token refund escrow that is no longer part of a live grant jar.
    function outstandingReservationExitClaims() external view returns (uint256);

    /// @dev Returns the address of the current owner.
    function owner() external view returns (address);

    function paused() external view returns (bool);

    /// @notice View one in-flight reservation by its canonical id.
    function pendingReservations(bytes32 reservationId) external view returns (PendingReservationV2 memory reservation);

    /// @notice Register a campaign, deriving an owner-bound id from `salt`.
    /// @dev Permissionless and zero-value. The campaign id is `campaignIdFor(msg.sender, salt)`, so a foreign registration derives a different id and can never collide with — and capture — another account's planned campaign. Registration must precede funding: a jar that already holds contributions cannot be registered, so an incidental or malicious pre-funding cannot seize a campaign. Funding remains the separate `contribute` action against `grantIdForCampaign(campaignId)`.
    /// @return campaignId The owner-bound campaign id now owned by the caller.
    function registerCampaignV1(bytes32 salt) external returns (bytes32 campaignId);

    /// @dev Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
    function renounceOwnership() external;

    function reservationExitSettlement(bytes32 reservationId) external view returns (ReservationExitSettlementV1 memory settlement);

    function reservationExitSnapshot(bytes32 reservationId, address contributor) external view returns (ReservationExitSnapshotV1 memory snapshot);

    /// @notice Gas overhead limits published for nodes to reserve gas for patronage checks
    function reserveGrantGasLimit() external view returns (uint256);

    /// @notice Reserve a grant's maximum transaction fee before user execution. Only callable by the Rust node (msg.sender == address(0)).
    /// @param reservationId Canonical transaction-derived reservation id. Reserve, settle, and cancel write only the selected grant, beneficiary authorization, and this unique reservation slot, so disjoint transactions never contend for a shared reservation cell.
    function reserveGrantV2(bytes32 reservationId, address sender, address target, bytes calldata input, uint256 maximumFee) external returns (bytes32 grantId);

    /// @notice Determine which onboarding grant, if any, should cover this transaction's gas. Returns grantId or bytes32(0) if no patron found. Priority: account assignment > referral encore > welcome jar.
    function resolveGrant(address sender, address target, bytes calldata input, uint256 fee) external view returns (bytes32);

    /// @notice Resolve a grant and return the effective jar and authorization bounds the node needs for pool-admission accounting in one system call.
    /// @dev For an ordinary grant the bounds are the stored beneficiary authorization. For a campaign voucher claim (`target == this`) there is no stored authorization yet, so the bounds come from the voucher itself: the single bootstrap transaction is admitted against the voucher's declared maximum transactions and lifetime spend with zero already consumed.
    function resolveGrantContext(address sender, address target, bytes calldata input, uint256 fee) external view returns (bytes32 grantId, uint256 jarBalance, uint32 maxTransactions, uint32 transactionsUsed, uint256 maxLifetimeSpend, uint256 lifetimeSpent);

    /// @notice Pre-burn one specific (beneficiary, nonce) voucher so it can never be claimed, without revoking the whole campaign.
    function revokeCampaignVoucherV1(bytes32 campaignId, address beneficiary, uint256 nonce) external;

    /// @notice Revoke one beneficiary's authorization without changing its jar assignment.
    function revokeGrantAuthorization(address beneficiary, bytes32 grantId) external;

    /// @notice Transfer campaign ownership and voucher-signing authority.
    function rotateCampaignOwnerV1(bytes32 campaignId, address newOwner) external;

    /// @notice Pause or resume all new claims for a campaign.
    function setCampaignRevokedV1(bytes32 campaignId, bool revoked) external;

    /// @notice Set one exact, bounded beneficiary route for a grant jar.
    function setGrantAuthorization(address beneficiary, bytes32 grantId, address target, bytes4 selector, uint32 maxTransactions, uint256 maxLifetimeSpend, uint64 expiry) external;

    function setPaused(bool paused_) external;

    /// @notice Link a referred address to the referrer's grant key. Contributor funds into `grantIdForReferral(referrer, referred)` separately.
    function setReferral(address referred, address referrer) external;

    function settleGrantGasLimit() external view returns (uint256);

    /// @notice Finalize one reservation at its actual transaction fee.
    /// @dev Settlement updates jar and authorization accounting only. It does not return a value and never touches the shared burn accumulator; block-final `accrueSettledBurnV2` reduces settled fees into `accruedBurn` exactly once. This path performs no external calls and is total for every `actualFee <= maximumFee`.
    function settleGrantV2(bytes32 reservationId, uint256 actualFee) external;

    /// @notice DiesisStaking address used by permissionless deferred burn flushing.
    function stakingAddress() external view returns (address);

    /// @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
    function transferOwnership(address newOwner) external;

    function updateGasLimits(uint256 reserveGas, uint256 settleGas) external;

    function updateStakingAddress(address staking_) external;

    /// @notice Reclaim a proportional share of a grant's remaining balance.
    /// @dev A withdrawal during an active reservation is a complete contributor exit: it records every live reservation-time claim before removing the caller's live share. This prevents a later refund from moving to a contributor who was never exposed to that reservation.
    function withdrawContribution(bytes32 grantId, uint256 amount) external;

    /// @notice Pull the settled or cancelled refund for one reservation-time contributor exit. Replay is rejected before any value is transferred.
    function withdrawReservationExit(bytes32 reservationId) external;

    receive() external payable;
}
