// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IDiesisPrivacyPools {
    error AlreadyRegistered();

    error InvalidProofLength();

    error InvalidVerifierIdentity();

    error NonCanonicalField();

    error NotInitialized();

    error NotPendingOwner();

    error NotRegisteredProvider();

    error RootMismatch();

    error Unauthorized();

    error ZeroAddress();

    error ZeroNullifier();

    error ZeroRoot();

    event AssociationSetUpdated(address indexed provider, bytes32 newRoot);

    event OwnershipTransferStarted(address indexed currentOwner, address indexed pendingOwner);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    event ProviderRegistered(address indexed provider, string name);

    function acceptOwnership() external;

    function artifactClass() external pure returns (bytes32);

    function associationVerifier() external pure returns (address);

    function initialized() external view returns (bool);

    function owner() external view returns (address);

    function pendingOwner() external view returns (address);

    function providerCount() external view returns (uint256);

    function providerList(uint256) external view returns (address);

    function providers(address) external view returns (string memory name, bool registered, bytes32 associationSetRoot);

    function registerProvider(address provider, string calldata name) external;

    function transferOwnership(address newOwner) external;

    function updateAssociationSet(bytes32 newRoot) external;

    function verifyAssociation(bytes calldata proof, bytes32 associationSetRoot, bytes32 nullifier, address provider) external view returns (bool);
}
