// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IValidatorShare {
    error BackingLotNotFound();

    error BackingLotTooSmall();

    error DifferentValidators();

    error DustBackingLot();

    error InsufficientBacking();

    error InvalidLotLimit();

    error InvalidShareTokenId();

    error NotPositionOwner();

    error RedemptionWorkLimit();

    error RepayExceedsBacking();

    error ZeroAddress();

    error ZeroShareAmount();

    event BackingAdded(uint32 indexed validator, uint256 indexed sourcePositionId, uint256 amount, uint256 lotRemaining);

    event BackingConsumed(uint32 indexed validator, uint256 indexed sourcePositionId, uint256 indexed receiverPositionId, uint256 amount, uint256 lotRemaining);

    event BackingRepaid(uint32 indexed validator, uint256 indexed sourcePositionId, uint256 amount, uint256 lotRemaining);

    event PositionBalanceSwapped(uint256 indexed fromTokenId, uint256 indexed toTokenId, uint256 swapAmount);

    event SharesMinted(uint256 indexed positionTokenId, uint256 indexed shareTokenId, uint256 shareAmount);

    event SharesRedeemed(uint256 indexed receiverPositionId, uint256 indexed shareTokenId, uint256 shareAmount, uint256 lotsConsumed);

    function DIESIS_POSITION() external view returns (address);

    /// @notice Maximum source lots an exact redemption may consume.
    function MAX_LOTS_PER_REDEMPTION() external view returns (uint256);

    /// @notice Minimum backing required when a source creates a new live FIFO lot.
    function MIN_BACKING_LOT() external view returns (uint256);

    /// @notice Inspect one stable live backing slot.
    function backingLot(uint32 validator, uint256 slot) external view returns (uint256 sourcePositionId, uint256 remaining, uint256 next, bool active);

    /// @notice Locate a source position's live lot, returning its absolute slot and remaining backing.
    function backingLotForPosition(uint32 validator, uint256 sourcePositionId) external view returns (uint256 slot, uint256 remaining, bool active);

    /// @notice Return the logical FIFO cursors, live lot count, and pooled backing.
    function backingPoolState(uint32 validator) external view returns (uint256 head, uint256 tail, uint256 liveLots, uint256 backing);

    /// @notice Mint validator shares backed by an owned position and add its debt to the validator FIFO.
    function mintShares(uint256 positionTokenId, uint256 shareAmount) external;

    /// @notice Outstanding share backing for one validator; equals its token supply.
    function pooledBacking(uint32 validator) external view returns (uint256);

    /// @notice Burn current-holder shares and move equal FIFO backing into an owned same-validator position.
    /// @param maxLots Caller-selected work bound from 1 through `MAX_LOTS_PER_REDEMPTION`.
    function redeemShares(uint256 receiverPositionId, uint256 shareTokenId, uint256 shareAmount, uint256 maxLots) external;

    /// @notice Burn caller-held shares to repay the caller's selected source position debt.
    function repayShares(uint256 sourcePositionId, uint256 shareAmount) external;

    function swapPositionBalance(uint256 fromTokenId, uint256 toTokenId, uint256 swapAmount) external;

    /// @notice Outstanding ERC-1155 supply for one validator share token ID.
    function totalSupply(uint256 shareTokenId) external view returns (uint256);

    function validatorShareTokenId(uint32 validator) external pure returns (uint256);
}
