// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IWrappedDS {
    error InsufficientAllowance(address spender, uint256 allowance, uint256 needed);

    error InsufficientBalance(address account, uint256 balance, uint256 needed);

    error TransferToZeroAddress();

    error WithdrawFailed();

    event Approval(address indexed owner, address indexed spender, uint256 amount);

    event Deposit(address indexed dst, uint256 amount);

    event Transfer(address indexed from, address indexed to, uint256 amount);

    event Withdrawal(address indexed src, uint256 amount);

    function allowance(address owner, address spender) external view returns (uint256);

    function approve(address spender, uint256 amount) external returns (bool);

    function balanceOf(address account) external view returns (uint256);

    function decimals() external view returns (uint8);

    function deposit() external payable;

    function name() external view returns (string memory);

    function symbol() external view returns (string memory);

    function totalSupply() external view returns (uint256);

    function transfer(address to, uint256 amount) external returns (bool);

    function transferFrom(address from, address to, uint256 amount) external returns (bool);

    function withdraw(uint256 amount) external;
}
