// SPDX-License-Identifier: MIT
// Generated by scripts/generate.py. Do not edit.
pragma solidity >=0.8.4 <0.9.0;

/// @notice Fixed system contract and precompile addresses from canonical.json.
// Every hex literal is validated as exactly 20 bytes by the generator.
// forge-lint: disable-start(unsafe-typecast)
library DiesisAddresses {
    address internal constant DIESIS_STAKING = address(bytes20(hex"d1e5150000000000000000000000000000000001"));
    address internal constant DIESIS_PATRON = address(bytes20(hex"d1e5150000000000000000000000000000000002"));
    address internal constant DIESIS_CONFIG = address(bytes20(hex"d1e5150000000000000000000000000000000003"));
    address internal constant BOOTSTRAP_ORACLE = address(bytes20(hex"d1e5150000000000000000000000000000000004"));
    address internal constant BOOTSTRAP_CONFIG = address(bytes20(hex"d1e5150000000000000000000000000000000005"));
    address internal constant DIESIS_STATE_WRITER = address(bytes20(hex"d1e5150000000000000000000000000000000010"));
    address internal constant DIESIS_POSITION = address(bytes20(hex"d1e5150000000000000000000000000000000020"));
    address internal constant DIESIS_BUNDLE_ESCROW = address(bytes20(hex"d1e515000000000000000000000000000000be5c"));
    address internal constant WRAPPED_DS = address(bytes20(hex"d1e51500000000000000000000000000000000d5"));
    address internal constant LIQUID_STAKED_DS = address(bytes20(hex"d1e51500000000000000000000000000000ac1d5"));
    address internal constant DIESIS_TEST_USD = address(bytes20(hex"d1e5150000000000000000000000000000000040"));
    address internal constant DIESIS_MARKETS = address(bytes20(hex"d1e515000000000000000000000000000000b00c"));
    address internal constant DIESIS_SPOT_BOOK = address(bytes20(hex"d1e515000000000000000000000000000000590d"));
    address internal constant DIESIS_PERPS_BOOK = address(bytes20(hex"d1e5150000000000000000000000000000009e29"));
    address internal constant DIESIS_MARGIN = address(bytes20(hex"d1e515000000000000000000000000000000a1ce"));
    address internal constant DIESIS_SETTLEMENT = address(bytes20(hex"d1e5150000000000000000000000000000005e71"));
    address internal constant DIESIS_SETTLEMENT_ROUTER = address(bytes20(hex"d1e5150000000000000000000000000000005e72"));
    address internal constant DIESIS_CONDUCTORS = address(bytes20(hex"00d1e5150000000000000000000000000000c0de"));
    address internal constant DIESIS_CORE_VAULT = address(bytes20(hex"00d1e5150000000000000000000000000000c04e"));
    address internal constant DIESIS_ISSUANCE_AUCTION = address(bytes20(hex"00d1e5150000000000000000000000000000a0c7"));
    address internal constant DIESIS_BUYBACK_BURN = address(bytes20(hex"0d1e51500000000000000000000000000000bb07"));
    address internal constant DIESIS_OPERATOR_BOND = address(bytes20(hex"00d1e5150000000000000000000000000000bacd"));
    address internal constant DIESIS_ERC20_FACTORY = address(bytes20(hex"00d1e5150000000000000000000000000000f00c"));
    address internal constant DIESIS_PERP_DEPLOY = address(bytes20(hex"00d1e5150000000000000000000000000000defb"));
    address internal constant DIESIS_NAME_REGISTRY = address(bytes20(hex"d1e5150000000000000000000000000000000050"));
    address internal constant DIESIS_BASE_REGISTRAR = address(bytes20(hex"d1e5150000000000000000000000000000000051"));
    address internal constant DIESIS_PUBLIC_RESOLVER = address(bytes20(hex"d1e5150000000000000000000000000000000052"));
    address internal constant DIESIS_REVERSE_REGISTRAR = address(bytes20(hex"d1e5150000000000000000000000000000000053"));
    address internal constant DIESIS_NAME_VERIFIER = address(bytes20(hex"d1e5150000000000000000000000000000000054"));
    address internal constant DIESIS_NAME_POLICY = address(bytes20(hex"d1e5150000000000000000000000000000000055"));
    address internal constant VRF = address(bytes20(hex"d1e5150000000000000000000000000000005eed"));
    address internal constant STEALTH_REGISTRY = address(bytes20(hex"d1e5150000000000000000000000000000facade"));
    address internal constant STEALTH_ANNOUNCER = address(bytes20(hex"d1e515000000000000000000000000000000ca5e"));
    address internal constant SHIELDED_POOL = address(bytes20(hex"d1e515000000000000000000000000000000fade"));
    address internal constant PRIVACY_POOLS = address(bytes20(hex"d1e5150000000000000000000000000000deface"));
    address internal constant GROTH16_VERIFIER = address(bytes20(hex"d1e515000000000000000000000000000000deed"));
    address internal constant SECP256R1 = address(bytes20(hex"0000000000000000000000000000000000000100"));
    address internal constant POSEIDON = address(bytes20(hex"0000000000000000000000000000000000000200"));
    address internal constant ML_DSA = address(bytes20(hex"0000000000000000000000000000000000000300"));
    address internal constant MULTICALL3 = address(bytes20(hex"ca11bde05977b3631167028862be2a173976ca11"));
    address internal constant PERMIT2 = address(bytes20(hex"000000000022d473030f116ddee9f6b43ac78ba3"));
}
