// SPDX-License-Identifier: MIT
// Generated by scripts/generate.py. Do not edit.
pragma solidity >=0.8.4 <0.9.0;

/// @notice Chain IDs from canonical.json.
library DiesisChains {
    uint256 internal constant MAINNET = 1980;
    uint256 internal constant TESTNET = 19803;
}
